using ECommerce.Application.Common.Exceptions;
using ECommerce.Application.Common.Interfaces;
using MediatR;

namespace ECommerce.Application.Products.Images.Commands.DeleteProductImage;

public sealed class DeleteProductImageCommandHandler : IRequestHandler<DeleteProductImageCommand>
{
    private readonly IProductImageRepository _repository;
    private readonly IUnitOfWork _unitOfWork;
    // Burada görsel silme işlemi için kalıcılık bağımlılıklarını hazırlıyorum.
    public DeleteProductImageCommandHandler(IProductImageRepository repository, IUnitOfWork unitOfWork)
    {
        _repository = repository; _unitOfWork = unitOfWork;
    }
    // Burada ana görsel silindiğinde kalan ilk görseli ana görsele çevirerek ürün medya kuralını koruyorum.
    public async Task Handle(DeleteProductImageCommand request, CancellationToken cancellationToken)
    {
        var image = await _repository.GetByIdForUpdateAsync(request.Id, cancellationToken)
            ?? throw new NotFoundException("Product image was not found.");
        if (image.IsMain)
        {
            var replacement = await _repository.GetFirstByProductIdForUpdateAsync(
                image.ProductId,
                image.Id,
                cancellationToken);
            replacement?.Update(
                replacement.ImageUrl,
                replacement.AltText,
                replacement.DisplayOrder,
                true,
                replacement.IsAltTextAutoGenerated);
        }

        _repository.Remove(image);
        await _unitOfWork.SaveChangesAsync(cancellationToken);
    }
}
