import Link from "next/link";
import { formatAccountingDate, formatAccountingMoney } from "@/modules/accounting/core/presentation";
import { PurchaseAllocationEditor } from "./purchase-allocation-editor";
import { PurchaseInvoiceExpenses } from "./purchase-invoice-expenses";
import { PurchaseInvoiceLifecycleActions } from "./purchase-invoice-lifecycle-actions";
import { invoiceStatusClass, invoiceStatusLabel } from "../presentation";
import type { AvailableStockMovement, ExpenseCategory, ProductVariantCostHistory, PurchaseInvoice, PurchaseInvoiceExpense } from "../types";

export function PurchaseInvoiceDetail({ invoice, expenses, categories, availableByLine, costHistory, secondaryDataUnavailable = false }: { invoice: PurchaseInvoice; expenses: PurchaseInvoiceExpense[]; categories: ExpenseCategory[]; availableByLine: Record<string, AvailableStockMovement[]>; costHistory: ProductVariantCostHistory[]; secondaryDataUnavailable?: boolean }) {
  const incompleteLines = invoice.lines.filter((line) => line.allocations.reduce((sum, allocation) => sum + allocation.allocatedQuantity, 0) !== line.stockQuantity).map((line) => line.lineNumber);
  return (
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_21rem]">
      <div className="min-w-0 space-y-4">
        {secondaryDataUnavailable ? <p role="alert" className="rounded-xl border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-950">Gider, tahsis seçimi veya maliyet geçmişi yardımcı verilerinden biri yüklenemedi. Belge tutarları güncel; eksik bölüm için sayfayı yenileyin.</p> : null}
        <DocumentFacts invoice={invoice} />
        <InvoiceLines invoice={invoice} availableByLine={availableByLine} />
        <PurchaseInvoiceExpenses invoiceId={invoice.id} currencyCode={invoice.currencyCode} status={invoice.status} lines={invoice.lines} expenses={expenses} categories={categories} />
        {invoice.status !== 1 ? <CostHistory invoice={invoice} items={costHistory} /> : null}
      </div>

      <aside className="space-y-4 xl:sticky xl:top-20">
        <section className="rounded-xl border border-border bg-surface p-4">
          <div className="flex items-center justify-between gap-3"><h2 className="text-sm font-semibold">Belge durumu</h2><span className={`rounded-md border px-2 py-0.5 text-xs font-bold ${invoiceStatusClass(invoice.status)}`}>{invoiceStatusLabel(invoice.status)}</span></div>
          <dl className="mt-4 space-y-3 text-xs"><RailFact label="Oluşturuldu" value={formatAccountingDate(invoice.createdAt)} /><RailFact label="Güncellendi" value={formatAccountingDate(invoice.updatedAt)} /><RailFact label="Post tarihi" value={formatAccountingDate(invoice.postedAt)} />{invoice.cancelledAt ? <RailFact label="İptal tarihi" value={formatAccountingDate(invoice.cancelledAt)} /> : null}</dl>
          {invoice.cancellationReason ? <p className="mt-3 rounded-lg border border-red-200 bg-red-50 p-2 text-xs leading-5 text-red-950"><strong>İptal gerekçesi:</strong> {invoice.cancellationReason}</p> : null}
        </section>
        <FinancialSummary invoice={invoice} />
        <section className="rounded-xl border border-border bg-surface p-4"><h2 className="text-sm font-semibold">Lifecycle işlemleri</h2><p className="mt-1 text-xs leading-5 text-muted">Draft iptali runtime tarafından desteklenmez. Her geçişten sonra belge yeniden okunur.</p><div className="mt-3"><PurchaseInvoiceLifecycleActions invoiceId={invoice.id} invoiceNumber={invoice.invoiceNumber} status={invoice.status} incompleteLines={incompleteLines} hasExpenses={expenses.length > 0} postDataUnavailable={secondaryDataUnavailable} /></div></section>
        {invoice.status === 1 ? <section className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><h2 className="font-semibold">Düzenleme sözleşmesi bekliyor</h2><p className="mt-2 leading-6">Detay API’si indirim ve uygunluk girdilerini geri döndürmediği için mevcut taslağın header/satır alanları kayıpsız düzenlenemez. Tahsis ve gider intent’leri ayrı olarak kullanılabilir.</p></section> : null}
      </aside>
    </div>
  );
}

function DocumentFacts({ invoice }: { invoice: PurchaseInvoice }) {
  const address = invoice.addressSnapshot || "Adres snapshot’ı yok";
  return <section className="rounded-xl border border-border bg-surface p-4 sm:p-5"><div className="border-b border-border pb-4"><h2 className="text-base font-semibold">Belge ve tedarikçi</h2><p className="mt-1 text-sm text-muted">Post anında korunan cari snapshot ve belge tarihleri.</p></div><dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Fact label="Tedarikçi" value={invoice.currentAccountName} href={`/accounting/current-accounts/${encodeURIComponent(invoice.currentAccountId)}`} /><Fact label="Fatura tarihi" value={formatAccountingDate(invoice.invoiceDate)} /><Fact label="Vade tarihi" value={formatAccountingDate(invoice.dueDate)} /><Fact label="Vergi numarası" value={invoice.taxNumberSnapshot || "—"} /><Fact label="Vergi dairesi" value={invoice.taxOfficeSnapshot || "—"} /><Fact label="İletişim" value={invoice.emailSnapshot || invoice.phoneNumberSnapshot || "—"} /><div className="sm:col-span-2 lg:col-span-3"><dt className="text-xs font-semibold text-muted">Adres</dt><dd className="mt-1 text-sm leading-6">{address}</dd></div>{invoice.description ? <div className="sm:col-span-2 lg:col-span-3"><dt className="text-xs font-semibold text-muted">Açıklama</dt><dd className="mt-1 text-sm leading-6">{invoice.description}</dd></div> : null}</dl></section>;
}

function InvoiceLines({ invoice, availableByLine }: { invoice: PurchaseInvoice; availableByLine: Record<string, AvailableStockMovement[]> }) {
  return <section className="overflow-hidden rounded-xl border border-border bg-surface"><div className="border-b border-border px-4 py-4 sm:px-5"><h2 className="text-base font-semibold">Belge satırları</h2><p className="mt-1 text-sm text-muted">Snapshot, API hesapları ve mevcut StockMovement tahsisleri.</p></div><div role="region" aria-label="Alış faturası satırları; yatay kaydırılabilir" tabIndex={0} className="overflow-x-auto outline-none focus:ring-2 focus:ring-inset focus:ring-focus/30"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="border-b border-border bg-surface-subtle/80 text-[11px] font-bold uppercase tracking-[0.07em] text-muted"><tr><th className="px-4 py-2.5">Satır / ürün</th><th className="px-3 py-2.5 text-right">Alış / stok</th><th className="px-3 py-2.5 text-right">Birim fiyat</th><th className="px-3 py-2.5 text-right">Net</th><th className="px-3 py-2.5 text-right">KDV</th><th className="px-3 py-2.5 text-right">Toplam</th><th className="px-4 py-2.5 text-right">Final birim maliyet</th></tr></thead><tbody className="divide-y divide-border">{invoice.lines.map((line) => { const allocated = line.allocations.reduce((sum, item) => sum + item.allocatedQuantity, 0); return <tr key={line.id}><td className="px-4 py-3"><p className="font-semibold">{line.lineNumber}. {line.productName}</p><p className="mt-0.5 text-xs text-muted">{line.variantName} · {line.sku}</p><p className={`mt-1 text-xs font-semibold ${allocated === line.stockQuantity ? "text-success" : "text-warning"}`}>Tahsis {allocated} / {line.stockQuantity} · {allocated === line.stockQuantity ? "Tamam" : "Eksik"}</p></td><td className="px-3 py-3 text-right tabular-nums">{line.purchaseQuantity} {line.unitOfMeasure}<span className="block text-xs text-muted">{line.stockQuantity} stok</span></td><td className="px-3 py-3 text-right tabular-nums">{formatAccountingMoney(line.enteredUnitPrice, invoice.currencyCode)}<span className="block text-xs text-muted">{line.priceEntryMode === 1 ? "KDV hariç" : "KDV dahil"}</span></td><td className="px-3 py-3 text-right tabular-nums">{formatAccountingMoney(line.netAmountExcludingVat, invoice.currencyCode)}</td><td className="px-3 py-3 text-right tabular-nums">{formatAccountingMoney(line.vatAmount, invoice.currencyCode)}<span className="block text-xs text-muted">%{line.vatRate}</span></td><td className="px-3 py-3 text-right font-semibold tabular-nums">{formatAccountingMoney(line.totalAmountIncludingVat, invoice.currencyCode)}</td><td className="px-4 py-3 text-right tabular-nums">{formatAccountingMoney(line.finalUnitCostExcludingVat, invoice.currencyCode)}<span className="block text-xs text-muted">KDV dahil {formatAccountingMoney(line.finalUnitCostIncludingVat, invoice.currencyCode)}</span></td></tr>; })}</tbody></table></div>{invoice.status === 1 ? invoice.lines.map((line) => <PurchaseAllocationEditor key={line.id} invoiceId={invoice.id} line={line} movements={availableByLine[line.id] ?? []} />) : null}</section>;
}

function FinancialSummary({ invoice }: { invoice: PurchaseInvoice }) {
  return <section className="rounded-xl border border-border bg-surface p-4"><h2 className="text-sm font-semibold">API mali özeti</h2><dl className="mt-3 space-y-2 text-sm"><MoneyFact label="Ara toplam (KDV hariç)" value={invoice.subtotalExcludingVat} currency={invoice.currencyCode} /><MoneyFact label="Toplam indirim" value={invoice.totalDiscountExcludingVat} currency={invoice.currencyCode} /><MoneyFact label="Net tutar" value={invoice.netAmountExcludingVat} currency={invoice.currencyCode} /><MoneyFact label="KDV" value={invoice.vatTotal} currency={invoice.currencyCode} /><MoneyFact label="Genel toplam" value={invoice.grandTotalIncludingVat} currency={invoice.currencyCode} strong /><div className="my-3 border-t border-border" /><MoneyFact label="Final maliyet (KDV hariç)" value={invoice.totalFinalCostExcludingVat} currency={invoice.currencyCode} strong /><MoneyFact label="Ödenen" value={invoice.paidAmount} currency={invoice.currencyCode} /><MoneyFact label="Kalan tedarikçi borcu" value={invoice.remainingAmount} currency={invoice.currencyCode} strong /></dl>{invoice.status !== 1 ? <Link href={`/accounting/current-accounts/${encodeURIComponent(invoice.currentAccountId)}`} className="mt-4 inline-flex min-h-9 items-center text-xs font-semibold text-primary hover:text-primary-hover">Cari ekstreyi aç →</Link> : null}</section>;
}

function CostHistory({ invoice, items }: { invoice: PurchaseInvoice; items: ProductVariantCostHistory[] }) {
  return <section className="rounded-xl border border-border bg-surface"><div className="border-b border-border px-4 py-4 sm:px-5"><h2 className="text-base font-semibold">FIFO maliyet etkisi</h2><p className="mt-1 text-sm text-muted">Varyant maliyet geçmişinde kaynak faturaya bağlı API kayıtları.</p></div>{items.length ? <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="text-left text-xs text-muted"><tr><th className="px-4 py-2.5">Varyant</th><th className="px-3 py-2.5">Geçerlilik</th><th className="px-3 py-2.5 text-right">Önceki maliyet</th><th className="px-3 py-2.5 text-right">Yeni maliyet</th><th className="px-4 py-2.5 text-right">Açılış miktarı</th></tr></thead><tbody className="divide-y divide-border">{items.map((item) => <tr key={item.id}><td className="px-4 py-3 font-mono text-xs">{item.productVariantId.slice(0, 12)}…</td><td className="px-3 py-3">{formatAccountingDate(item.validFrom)}</td><td className="px-3 py-3 text-right tabular-nums">{item.previousCostExcludingVat === null || item.previousCostExcludingVat === undefined ? "—" : formatAccountingMoney(item.previousCostExcludingVat, invoice.currencyCode)}</td><td className="px-3 py-3 text-right font-semibold tabular-nums">{formatAccountingMoney(item.newCostExcludingVat, invoice.currencyCode)}</td><td className="px-4 py-3 text-right tabular-nums">{item.openingStockQuantity}</td></tr>)}</tbody></table></div> : <p className="px-5 py-8 text-center text-sm text-muted">Bu faturaya bağlı varyant maliyet geçmişi kaydı bulunamadı.</p>}</section>;
}

function Fact({ label, value, href }: { label: string; value: string; href?: string }) { return <div><dt className="text-xs font-semibold text-muted">{label}</dt><dd className="mt-1 text-sm font-medium">{href ? <Link href={href} className="text-primary hover:text-primary-hover">{value}</Link> : value}</dd></div>; }
function RailFact({ label, value }: { label: string; value: string }) { return <div className="flex items-start justify-between gap-3"><dt className="text-muted">{label}</dt><dd className="text-right font-medium">{value}</dd></div>; }
function MoneyFact({ label, value, currency, strong }: { label: string; value: number; currency: string; strong?: boolean }) { return <div className="flex items-start justify-between gap-3"><dt className="text-muted">{label}</dt><dd className={`text-right tabular-nums ${strong ? "font-bold text-foreground" : "font-medium"}`}>{formatAccountingMoney(value, currency)}</dd></div>; }
