"use client";

import Link from "next/link";
import { useActionState, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { createPaymentAction } from "../actions";
import { formatAccountingDate, formatMoney } from "../presentation";
import type { BankAccount, CashAccount, CurrentAccountOption, OpenItem, PaymentSetup } from "../types";
import { initialPaymentFormState } from "../types";

export function PaymentSetupForm({ accounts, setup }: { accounts: CurrentAccountOption[]; setup: PaymentSetup | null }) {
  return <form method="get" className="rounded-xl border border-border bg-surface p-5"><fieldset><legend className="font-semibold">1. İşlem kapsamını seçin</legend><p className="mt-1 text-sm text-muted">Cari seçildikten sonra yalnız o cariye ait güncel açık kalemler sunucudan okunur.</p><div className="mt-4 grid gap-4 md:grid-cols-[14rem_minmax(0,1fr)_auto]"><label className="text-sm font-medium">İşlem türü<select name="type" defaultValue={setup?.type ?? 1} className="mt-1.5 min-h-10 w-full rounded-lg border border-border-strong bg-surface px-3"><option value="1">Müşteri tahsilatı</option><option value="2">Tedarikçi ödemesi</option></select></label><label className="text-sm font-medium">Cari hesap<select name="currentAccountId" required defaultValue={setup?.currentAccountId ?? ""} className="mt-1.5 min-h-10 w-full rounded-lg border border-border-strong bg-surface px-3"><option value="">Cari seçin</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><button type="submit" className="min-h-10 self-end rounded-lg border border-primary px-4 text-sm font-semibold text-primary hover:bg-primary-soft/30">Açık kalemleri getir</button></div></fieldset></form>;
}

export function PaymentCreateForm({ setup, account, openItems, cashAccounts, bankAccounts }: { setup: PaymentSetup; account: CurrentAccountOption; openItems: OpenItem[]; cashAccounts: CashAccount[]; bankAccounts: BankAccount[] }) {
  const router = useRouter(); const formRef = useRef<HTMLFormElement>(null); const errorRef = useRef<HTMLDivElement>(null); const submitGuard = useRef(false); const [state, action, pending] = useActionState(createPaymentAction, initialPaymentFormState); const [amountCents, setAmountCents] = useState(0); const [allocatedCents, setAllocatedCents] = useState(0);
  useEffect(() => { if (state.redirectHref) { router.replace(state.redirectHref); router.refresh(); } }, [router, state.redirectHref]);
  useEffect(() => { if (state.status === "error") errorRef.current?.focus(); submitGuard.current = false; if (state.refresh) router.refresh(); }, [router, state]);
  const recompute = () => { const form = formRef.current; if (!form) return; const toCents = (value: FormDataEntryValue | null) => Math.round(Number(String(value ?? "").replace(",", ".")) * 100) || 0; const data = new FormData(form); setAmountCents(toCents(data.get("amount"))); setAllocatedCents(openItems.reduce((sum, item) => sum + toCents(data.get(`allocation:${item.id}`)), 0)); };
  const rotateIntent = (target: EventTarget | null) => { const element = target as HTMLInputElement | null; if (element?.name === "idempotencyKey") return; const hidden = formRef.current?.elements.namedItem("idempotencyKey") as HTMLInputElement | null; if (hidden) hidden.value = crypto.randomUUID(); recompute(); };
  const defaultDate = new Date().toISOString().slice(0, 10); const isAdvance = setup.type === 2 && allocatedCents === 0; const difference = amountCents - allocatedCents;
  return <form ref={formRef} action={action} onInput={(event) => rotateIntent(event.target)} onSubmit={(event) => { if (submitGuard.current) event.preventDefault(); else submitGuard.current = true; }} className="grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_20rem]"><input type="hidden" name="idempotencyKey" defaultValue={state.draft?.idempotencyKey ?? crypto.randomUUID()} /><input type="hidden" name="currentAccountId" value={setup.currentAccountId} /><input type="hidden" name="type" value={setup.type} />
    {state.status === "error" ? <div ref={errorRef} role="alert" tabIndex={-1} className="rounded-xl border border-danger/30 bg-red-50 px-4 py-3 text-sm text-red-900 outline-none focus:ring-2 focus:ring-danger/30 lg:col-span-2"><strong>{state.message}</strong>{state.fieldErrors ? <ul className="mt-2 list-disc pl-5">{Object.entries(state.fieldErrors).flatMap(([key, messages]) => messages.map((message) => <li key={`${key}-${message}`}>{message}</li>))}</ul> : null}{state.traceId ? <span className="mt-1 block text-xs">Takip kodu: {state.traceId}</span> : null}</div> : null}
    <div className="space-y-4"><section className="rounded-xl border border-border bg-surface p-5"><h2 className="font-semibold">2. Makbuz bilgileri</h2><p className="mt-1 text-sm text-muted"><strong>{account.name}</strong> · {setup.type === 1 ? "müşteri tahsilatı" : "tedarikçi ödemesi"}</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field name="amount" label="İşlem tutarı" type="text" inputMode="decimal" required defaultValue={state.draft?.amount} /><Field name="paymentDate" label="İşlem tarihi" type="date" required defaultValue={state.draft?.paymentDate ?? defaultDate} /></div><label className="mt-4 block text-sm font-medium">Kasa veya banka hesabı *<select name="accountChoice" required defaultValue={state.draft ? `${state.draft.accountKind}:${state.draft.financialAccountId}` : ""} className="mt-1.5 min-h-10 w-full rounded-lg border border-border-strong bg-surface px-3"><option value="">Hesap seçin</option><optgroup label="Kasalar">{cashAccounts.map((item) => <option key={item.id} value={`cash:${item.id}`}>{item.code} · {item.name} · {formatMoney(item.balance)}</option>)}</optgroup><optgroup label="Banka hesapları">{bankAccounts.map((item) => <option key={item.id} value={`bank:${item.id}`}>{item.code} · {item.name} · {formatMoney(item.balance)}</option>)}</optgroup></select></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field name="referenceNumber" label="Referans" maxLength={100} defaultValue={state.draft?.referenceNumber} /><label className="text-sm font-medium">Açıklama<textarea name="description" maxLength={500} defaultValue={state.draft?.description} rows={3} className="mt-1.5 w-full rounded-lg border border-border-strong bg-surface px-3 py-2" /></label></div></section>
      <section className="rounded-xl border border-border bg-surface p-5"><h2 className="font-semibold">3. Açık kalem dağıtımı</h2><p className="mt-1 text-sm text-muted">{setup.type === 1 ? "Tahsilat tutarının tamamını bir veya daha fazla müşteri alacağına dağıtın." : "Borcun tamamına dağıtın veya bütün alanları boş bırakıp tedarikçi avansı kaydedin."}</p>{openItems.length ? <div className="mt-4 overflow-x-auto" tabIndex={0} aria-label="Dağıtıma açık kalemler"><table className="min-w-[650px] w-full text-sm"><thead><tr className="border-b border-border text-left text-xs uppercase text-muted"><th className="py-2 pr-3">Belge</th><th className="px-3 py-2">Tarih / vade</th><th className="px-3 py-2 text-right">Açık</th><th className="py-2 pl-3 text-right">Dağıtım</th></tr></thead><tbody>{openItems.map((item) => <tr key={item.id} className="border-b border-border/70"><td className="py-3 pr-3"><input type="hidden" name="allocationId" value={item.id} /><span className="font-mono text-xs">{item.id.slice(0, 8)}</span></td><td className="px-3 py-3">{item.date ? formatAccountingDate(item.date) : "—"}<span className="block text-xs text-muted">Vade: {item.dueDate ? formatAccountingDate(item.dueDate) : "—"}</span></td><td className="px-3 py-3 text-right font-semibold">{formatMoney(item.tertiaryAmount)}</td><td className="py-3 pl-3 text-right"><label className="sr-only" htmlFor={`allocation-${item.id}`}>{item.id.slice(0, 8)} açık kalemine dağıtım</label><input id={`allocation-${item.id}`} name={`allocation:${item.id}`} type="number" inputMode="decimal" min="0.01" max={item.tertiaryAmount} step="0.01" placeholder="0,00" defaultValue={state.draft?.allocations[item.id]} className="min-h-10 w-32 rounded-lg border border-border-strong px-3 text-right tabular-nums" /></td></tr>)}</tbody></table></div> : <div className="mt-4 rounded-lg border border-dashed border-border-strong p-4 text-sm text-muted">Bu cari için dağıtıma açık {setup.type === 1 ? "müşteri alacağı" : "tedarikçi borcu"} bulunmuyor.{setup.type === 2 ? " Yine de dağıtımsız avans kaydedebilirsiniz." : " Tahsilat oluşturulamaz."}</div>}</section></div>
    <aside className="rounded-xl border border-primary/20 bg-primary-soft/20 p-5 lg:sticky lg:top-5"><h2 className="font-semibold">İşlem özeti</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-muted">İşlem tutarı</dt><dd className="font-semibold tabular-nums">{formatMoney(amountCents / 100)}</dd></div><div className="flex justify-between"><dt className="text-muted">Dağıtılan</dt><dd className="font-semibold tabular-nums">{formatMoney(allocatedCents / 100)}</dd></div><div className="flex justify-between border-t border-border pt-3"><dt className="text-muted">Fark</dt><dd className={`font-bold tabular-nums ${difference === 0 ? "text-emerald-700" : "text-amber-800"}`}>{formatMoney(difference / 100)}</dd></div></dl><p aria-live="polite" className="mt-4 rounded-lg bg-surface px-3 py-2 text-xs leading-5 text-muted">{setup.type === 2 && isAdvance ? "Dağıtım yok: tutarın tamamı tedarikçi avansı olarak kalır." : difference === 0 && amountCents > 0 ? "Dağıtım toplamı işlem tutarıyla eşleşiyor." : "Dağıtım toplamı işlem tutarına tam eşit olmalıdır."}</p><button type="submit" disabled={pending || setup.type === 1 && !openItems.length} className="mt-4 min-h-11 w-full cursor-pointer rounded-lg bg-primary px-4 text-sm font-semibold text-white hover:bg-primary-hover disabled:cursor-not-allowed disabled:opacity-60">{pending ? "Kaydediliyor…" : setup.type === 1 ? "Tahsilatı kaydet" : isAdvance ? "Tedarikçi avansını kaydet" : "Tedarikçi ödemesini kaydet"}</button><Link href="/accounting/payments" className="mt-2 inline-flex min-h-10 w-full items-center justify-center text-sm font-medium text-muted hover:text-foreground">Vazgeç</Link><p className="mt-3 text-xs leading-5 text-muted">Bakiye ve açık tutarlar API tarafından doğrulanır. Çakışmada otomatik tekrar yapılmaz.</p></aside>
  </form>;
}
function Field({ name, label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { name: string; label: string }) { return <label className="text-sm font-medium">{label}{props.required ? " *" : ""}<input id={name} name={name} {...props} className="mt-1.5 min-h-10 w-full rounded-lg border border-border-strong bg-surface px-3" /></label>; }
