import Link from "next/link";
import type { PaymentListQuery, PaymentPage } from "../types";
import { buildPaymentListHref } from "../query";
import { formatAccountingDate, formatMoney, paymentStatusClass, paymentStatusLabel, paymentTypeLabel } from "../presentation";

export function PaymentRegister({ page, query, accountNames }: { page: PaymentPage; query: PaymentListQuery; accountNames: Map<string, string> }) {
  if (!page.items.length) return <section className="rounded-xl border border-dashed border-border-strong bg-surface p-8 text-center"><h2 className="text-lg font-semibold">Henüz ödeme veya tahsilat yok</h2><p className="mt-2 text-sm text-muted">İlk müşteri tahsilatını ya da tedarikçi ödemesini açık kalemlerine bağlayın.</p><Link href="/accounting/payments/new" className="mt-5 inline-flex min-h-10 items-center rounded-lg bg-primary px-4 text-sm font-semibold text-white hover:bg-primary-hover">İlk işlemi oluştur</Link></section>;
  return <section className="overflow-hidden rounded-xl border border-border bg-surface" aria-label="Ödeme ve tahsilat sicili"><div className="overflow-x-auto" tabIndex={0}><table className="min-w-[860px] w-full text-left text-sm"><thead className="bg-surface-subtle text-xs uppercase tracking-wide text-muted"><tr><th className="px-4 py-3">Tarih</th><th className="px-4 py-3">İşlem</th><th className="px-4 py-3">Cari hesap</th><th className="px-4 py-3">Yön</th><th className="px-4 py-3">Durum</th><th className="px-4 py-3 text-right">Tutar</th></tr></thead><tbody className="divide-y divide-border">{page.items.map((item) => <tr key={item.id} className="hover:bg-primary-soft/10"><td className="px-4 py-3 tabular-nums">{formatAccountingDate(item.paymentDate)}</td><td className="px-4 py-3"><Link href={`/accounting/payments/${item.id}`} className="font-semibold text-primary underline-offset-4 hover:underline">{paymentTypeLabel(item.type)}</Link><span className="mt-0.5 block font-mono text-[11px] text-muted">{item.id.slice(0, 8)}</span></td><td className="px-4 py-3"><Link href={`/accounting/current-accounts/${item.currentAccountId}`} className="hover:text-primary hover:underline">{accountNames.get(item.currentAccountId) ?? "Cari kayıt"}</Link></td><td className="px-4 py-3">{item.direction === 1 ? "Giriş" : "Çıkış"}</td><td className="px-4 py-3"><span className={`inline-flex rounded-md border px-2 py-1 text-xs font-semibold ${paymentStatusClass(item.status)}`}>{paymentStatusLabel(item.status)}</span></td><td className="px-4 py-3 text-right font-semibold tabular-nums">{formatMoney(item.amount, item.currencyCode)}</td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-border px-4 py-3 text-sm"><span className="text-muted">Sayfa {page.pageNumber} / {Math.max(page.totalPages, 1)} · {page.totalCount} kayıt</span><div className="flex gap-2">{page.hasPreviousPage ? <Link href={buildPaymentListHref(query, page.pageNumber - 1)} className="inline-flex min-h-9 items-center rounded-lg border border-border-strong px-3 font-medium hover:bg-surface-subtle">Önceki</Link> : null}{page.hasNextPage ? <Link href={buildPaymentListHref(query, page.pageNumber + 1)} className="inline-flex min-h-9 items-center rounded-lg border border-border-strong px-3 font-medium hover:bg-surface-subtle">Sonraki</Link> : null}</div></div></section>;
}
