import Link from "next/link";
import type { BankAccount, CashAccount, CurrentAccountOption, Payment } from "../types";
import { formatAccountingDate, formatMoney, paymentStatusClass, paymentStatusLabel, paymentTypeLabel } from "../presentation";
import { PaymentLifecycleActions } from "./payment-lifecycle-actions";

export function PaymentDetail({ payment, account, cashAccount, bankAccount }: { payment: Payment; account?: CurrentAccountOption; cashAccount?: CashAccount; bankAccount?: BankAccount }) {
  const cancelled = payment.status !== 1;
  return <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_22rem]"><div className="space-y-5"><section className="rounded-xl border border-border bg-surface p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted">Ödeme makbuzu</p><h2 className="mt-1 text-xl font-semibold">{paymentTypeLabel(payment.type)}</h2></div><span className={`rounded-md border px-2.5 py-1 text-xs font-bold ${paymentStatusClass(payment.status)}`}>{paymentStatusLabel(payment.status)}</span></div><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Datum label="Cari hesap" value={account ? account.name : payment.currentAccountId.slice(0, 8)} href={`/accounting/current-accounts/${payment.currentAccountId}`} /><Datum label="İşlem tarihi" value={formatAccountingDate(payment.paymentDate)} /><Datum label="Yön" value={payment.direction === 1 ? "Giriş" : "Çıkış"} /><Datum label="Finans hesabı" value={cashAccount ? `Kasa · ${cashAccount.name}` : bankAccount ? `Banka · ${bankAccount.name}` : "Hesap kaydı bulunamadı"} /><Datum label="Referans" value={payment.referenceNumber || "—"} /><Datum label="Kayıt" value={payment.id} mono /></dl>{payment.description ? <div className="mt-5 border-t border-border pt-4"><p className="text-xs font-semibold uppercase text-muted">Açıklama</p><p className="mt-1 text-sm leading-6">{payment.description}</p></div> : null}</section>
    <section className="rounded-xl border border-border bg-surface p-5"><h2 className="font-semibold">Açık kalem dağıtımları</h2>{cancelled && !payment.allocations.length ? <div className="mt-3 rounded-lg border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-950">API iptal edilmiş dağıtım satırlarını detay modelinde projekte etmiyor. Aşağıdaki “dağıtılmamış” değer kullanılabilir avans anlamına gelmez; iptal ve ters kayıt denetim izi korunur.</div> : null}{payment.allocations.length ? <div className="mt-4 overflow-x-auto" tabIndex={0}><table className="min-w-[620px] w-full text-sm"><thead><tr className="border-b border-border text-left text-xs uppercase text-muted"><th className="py-2">Cari hareket</th><th className="px-3 py-2">Kaynak</th><th className="px-3 py-2">Ters kayıt</th><th className="py-2 text-right">Tutar</th></tr></thead><tbody>{payment.allocations.map((item) => <tr key={item.id} className="border-b border-border/70"><td className="py-3 font-mono text-xs">{item.currentAccountTransactionId}</td><td className="px-3 py-3 font-mono text-xs">{item.sourceId.slice(0, 8)}</td><td className="px-3 py-3">{item.isReversed ? "Evet" : "Hayır"}</td><td className="py-3 text-right font-semibold">{formatMoney(item.allocatedAmount)}</td></tr>)}</tbody></table></div> : !cancelled ? <p className="mt-3 text-sm text-muted">Dağıtım yok; bu kayıt tedarikçi avansıdır.</p> : null}</section></div>
    <aside className="space-y-4"><section className="rounded-xl border border-primary/20 bg-primary-soft/20 p-5"><h2 className="font-semibold">Tutar özeti</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-muted">Toplam</dt><dd className="font-bold">{formatMoney(payment.amount)}</dd></div><div className="flex justify-between"><dt className="text-muted">Dağıtılan</dt><dd>{cancelled ? "İptal öncesi değer API'de yok" : formatMoney(payment.allocatedAmount)}</dd></div><div className="flex justify-between border-t border-border pt-3"><dt className="text-muted">Dağıtılmamış</dt><dd>{cancelled ? "Uygulanamaz" : formatMoney(payment.unallocatedAmount)}</dd></div></dl></section>{payment.status === 1 ? <PaymentLifecycleActions payment={payment} /> : <section className="rounded-xl border border-border bg-surface p-5"><h2 className="font-semibold">İptal denetimi</h2><p className="mt-2 text-sm text-muted">{payment.cancellationReason ?? "Gerekçe API yanıtında bulunmuyor."}</p>{payment.cancelledAt ? <p className="mt-2 text-xs text-muted">{formatAccountingDate(payment.cancelledAt)}</p> : null}</section>}</aside></div>;
}
function Datum({ label, value, href, mono }: { label: string; value: string; href?: string; mono?: boolean }) { return <div><dt className="text-xs font-semibold uppercase text-muted">{label}</dt><dd className={`mt-1 break-words text-sm ${mono ? "font-mono text-xs" : "font-medium"}`}>{href ? <Link href={href} className="text-primary hover:underline">{value}</Link> : value}</dd></div>; }
