import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ApiError } from "@/lib/api/problem";
import { requireAdminPageSession } from "@/lib/auth/session";
import { PageHeader } from "@/modules/admin-shell/components/page-header";
import { getSalesInvoice } from "@/modules/accounting/sales/api";
import { SalesInvoiceDetail } from "@/modules/accounting/sales/components/sales-document-detail";
import { documentStatusClass, documentStatusLabel } from "@/modules/accounting/sales/presentation";

export const metadata: Metadata = { title: "Satış Faturası Detayı" };
export default async function SalesInvoiceDetailPage({ params, searchParams }: { params: Promise<{ salesInvoiceId: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) { const [{ salesInvoiceId }, query] = await Promise.all([params, searchParams]); const session = await requireAdminPageSession(`/accounting/sales-invoices/${encodeURIComponent(salesInvoiceId)}`); let invoice; try { invoice = await getSalesInvoice(salesInvoiceId, session); } catch (error) { if (error instanceof ApiError && error.problem.status === 404) notFound(); throw error; } const notice = query.created === "1" ? "Satış faturası ve bağlı muhasebe satışı taslak olarak oluşturuldu." : query.createdFromOrder === "1" ? invoice.status === 2 ? "Fatura post edilmiş satışa bağlandı ve doğrudan post edilmiş olarak oluşturuldu." : "Fatura satış taslağına bağlandı." : query.updated === "1" ? "Satış faturası taslağı güncellendi." : null; return <div className="mx-auto w-full max-w-screen-2xl"><PageHeader title={invoice.invoiceNumber} description={invoice.currentAccountName} backHref="/accounting/sales-invoices" actions={<>{invoice.status === 1 ? <Link href={`/accounting/sales-invoices/${encodeURIComponent(invoice.id)}/edit`} className="inline-flex min-h-10 items-center rounded-lg border border-border-strong bg-surface px-3.5 text-sm font-semibold hover:bg-surface-subtle">Taslağı düzenle</Link> : null}<span className={`inline-flex rounded-md border px-2.5 py-1 text-xs font-bold ${documentStatusClass(invoice.status)}`}>{documentStatusLabel(invoice.status)}</span></>} />{notice ? <p role="status" className="mb-4 rounded-xl border border-emerald-300 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-900">{notice}</p> : null}<SalesInvoiceDetail invoice={invoice} /></div>; }
