"use server";

import { revalidatePath } from "next/cache";
import { ApiError } from "@/lib/api/problem";
import { requireAdminActionSession } from "@/lib/auth/session";
import { createBankAccount, createBankTransfer, createCashAccount, createFinancialTransaction, reverseFinancialTransaction } from "./api";
import { parseBankAccount, parseBankTransfer, parseCashAccount, parseManualTransaction } from "./form-data";
import type { TreasuryFormState } from "./types";

export async function createCashAccountAction(_p: TreasuryFormState, data: FormData): Promise<TreasuryFormState> { const parsed = parseCashAccount(data); if (!parsed.ok) return { status: "error", message: parsed.message, fieldErrors: parsed.fieldErrors }; try { const session = await requireAdminActionSession(); const account = await createCashAccount(parsed.input, session); refreshTreasury(); return { status: "success", message: "Kasa hesabı oluşturuldu.", redirectHref: `/accounting/treasury/cash/${account.id}?created=1` }; } catch (e) { return treasuryError(e, "Kasa hesabı oluşturulamadı.", "Kasa kodu başka bir kayıtla çakışıyor."); } }
export async function createBankAccountAction(_p: TreasuryFormState, data: FormData): Promise<TreasuryFormState> { const parsed = parseBankAccount(data); if (!parsed.ok) return { status: "error", message: parsed.message, fieldErrors: parsed.fieldErrors }; try { const session = await requireAdminActionSession(); const account = await createBankAccount(parsed.input, session); refreshTreasury(); return { status: "success", message: "Banka hesabı oluşturuldu.", redirectHref: `/accounting/treasury/bank/${account.id}?created=1` }; } catch (e) { return treasuryError(e, "Banka hesabı oluşturulamadı.", "Hesap kodu veya IBAN başka bir kayıtla çakışıyor."); } }
export async function createManualTransactionAction(_p: TreasuryFormState, data: FormData): Promise<TreasuryFormState> { const parsed = parseManualTransaction(data); if (!parsed.ok) return { status: "error", message: parsed.message, fieldErrors: parsed.fieldErrors }; try { const session = await requireAdminActionSession(); const tx = await createFinancialTransaction(parsed.input, parsed.idempotencyKey!, session); refreshTreasury(); const kind = tx.cashAccountId ? "cash" : "bank"; const id = tx.cashAccountId ?? tx.bankAccountId!; return { status: "success", message: "Manuel finans hareketi kaydedildi.", redirectHref: `/accounting/treasury/${kind}/${id}?createdTransaction=1` }; } catch (e) { return treasuryError(e, "Finans hareketi kaydedilemedi.", "İşlem anahtarı daha önce kullanılmış veya hesap durumu değişmiş. Ekstreyi kontrol edin; otomatik retry yapılmadı.", true); } }
export async function createBankTransferAction(_p: TreasuryFormState, data: FormData): Promise<TreasuryFormState> { const parsed = parseBankTransfer(data); if (!parsed.ok) return { status: "error", message: parsed.message, fieldErrors: parsed.fieldErrors }; try { const session = await requireAdminActionSession(); const result = await createBankTransfer(parsed.input, parsed.idempotencyKey!, session); if (result.transferOut.sourceId !== result.transferIn.sourceId || result.transferOut.type !== 21 || result.transferIn.type !== 20) return { status: "error", message: "API transfer çifti beklenen atomik sözleşmeyle eşleşmedi. Her iki ekstreyi kontrol edin." }; refreshTreasury(); return { status: "success", message: "Banka transferi iki yönlü ve atomik olarak kaydedildi.", redirectHref: `/accounting/treasury/bank/${parsed.input.fromBankAccountId}?createdTransfer=1` }; } catch (e) { return treasuryError(e, "Banka transferi kaydedilemedi.", "İşlem anahtarı daha önce kullanılmış veya hesap durumu değişmiş. Her iki ekstreyi kontrol edin; otomatik retry yapılmadı.", true); } }
export async function reverseFinancialTransactionAction(id: string, accountPath: string, _p: TreasuryFormState, data: FormData): Promise<TreasuryFormState> { const reason = typeof data.get("reason") === "string" ? String(data.get("reason")).trim() : ""; if (!reason || reason.length > 500) return { status: "error", message: "Ters kayıt gerekçesi 1–500 karakter olmalıdır." }; try { const session = await requireAdminActionSession(); const result = await reverseFinancialTransaction(id, reason, session); refreshTreasury(); revalidatePath(accountPath); return { status: "success", message: result.alreadyProcessed ? "Hareket daha önce terslenmişti; ekstre yeniden okundu." : "Ters kayıt oluşturuldu; özgün hareket korunarak ekstre yeniden okundu.", refresh: true }; } catch (e) { return treasuryError(e, "Ters kayıt oluşturulamadı.", "Hareket daha önce terslenmiş, ödeme kaynaklı veya artık uygun değil. Ekstre yeniden okunacak.", true); } }
function refreshTreasury(): void { revalidatePath("/accounting"); revalidatePath("/accounting/treasury"); revalidatePath("/accounting/payments"); }
function treasuryError(error: unknown, fallback: string, conflict: string, refresh = false): TreasuryFormState { if (!(error instanceof ApiError)) return { status: "error", message: fallback }; const p = error.problem; const message = p.status === 401 ? "Oturumunuz sona erdi. Yeniden giriş yapın." : p.status === 403 ? "Bu işlem için yönetici yetkiniz yok." : p.status === 404 ? "Finans hesabı veya hareket artık bulunamıyor." : p.status === 409 ? conflict : p.status === 429 ? p.retryAfter ? `İstek sınırına ulaşıldı. ${p.retryAfter} sonra yeniden deneyin.` : "İstek sınırına ulaşıldı." : p.detail || p.title || fallback; return { status: "error", message, fieldErrors: p.errors, traceId: p.traceId, retryAfter: p.retryAfter, refresh: refresh && p.status === 409 }; }
