import type { BankAccountInput, BankTransferInput, FinancialAccountInput, FinancialTransactionInput } from "./types";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const MONEY = /^\d{1,16}(?:[.,]\d{1,2})?$/;
const text = (data: FormData, name: string) => typeof data.get(name) === "string" ? String(data.get(name)).trim() : "";
type Result<T> = { ok: true; input: T; idempotencyKey?: string } | { ok: false; message: string; fieldErrors: Record<string, string[]> };
const fail = (fieldErrors: Record<string, string[]>, message = "İşlem kaydedilmedi. İşaretli alanları düzeltin.") => ({ ok: false as const, message, fieldErrors });

export function parseCashAccount(data: FormData): Result<FinancialAccountInput> { const code = text(data, "code"); const name = text(data, "name"); const e: Record<string, string[]> = {}; if (!code || code.length > 50) e.code = ["Kasa kodu 1–50 karakter olmalıdır."]; if (!name || name.length > 150) e.name = ["Kasa adı 1–150 karakter olmalıdır."]; return Object.keys(e).length ? fail(e) : { ok: true, input: { code, name, currencyCode: "TRY" } }; }
export function parseBankAccount(data: FormData): Result<BankAccountInput> { const code = text(data, "code"); const name = text(data, "name"); const bankName = text(data, "bankName"); const iban = text(data, "iban").replace(/\s/g, "").toUpperCase(); const e: Record<string, string[]> = {}; if (!code || code.length > 50) e.code = ["Hesap kodu 1–50 karakter olmalıdır."]; if (!name || name.length > 150) e.name = ["Hesap adı 1–150 karakter olmalıdır."]; if (!bankName || bankName.length > 150) e.bankName = ["Banka adı 1–150 karakter olmalıdır."]; if (iban.length > 34) e.iban = ["IBAN en fazla 34 karakter olabilir."]; return Object.keys(e).length ? fail(e) : { ok: true, input: { code, name, bankName, iban: iban || null, currencyCode: "TRY" } }; }

export function parseManualTransaction(data: FormData): Result<FinancialTransactionInput> {
  const type = Number(text(data, "type")); const amountRaw = text(data, "amount"); const amount = Number(amountRaw.replace(",", ".")); const date = text(data, "transactionDate"); const [kind, accountId = ""] = text(data, "accountChoice").split(":", 2); const description = text(data, "description"); const idempotencyKey = text(data, "idempotencyKey"); const e: Record<string, string[]> = {};
  if (![10, 11, 40, 41, 50].includes(type)) e.type = ["Bu işlem türü manuel kayıt için güvenli değil."]; if (!MONEY.test(amountRaw) || amount <= 0) e.amount = ["Tutar sıfırdan büyük ve en fazla 2 ondalıklı olmalıdır."]; if (!date || Number.isNaN(Date.parse(`${date}T00:00:00Z`))) e.transactionDate = ["Geçerli bir tarih girin."]; if (!UUID.test(accountId)) e.accountId = ["Aktif bir finans hesabı seçin."]; if (([10, 11].includes(type) && kind !== "cash") || ([40, 41].includes(type) && kind !== "bank") || !["cash", "bank"].includes(kind)) e.accountKind = ["İşlem türüyle uyumlu hesap seçin."]; if (!UUID.test(idempotencyKey)) e.idempotencyKey = ["İşlem anahtarı geçersiz; sayfayı yenileyin."]; if (description.length > 500) e.description = ["Açıklama en fazla 500 karakter olabilir."];
  return Object.keys(e).length ? fail(e) : { ok: true, idempotencyKey, input: { type: type as 10 | 11 | 40 | 41 | 50, amount, transactionDate: `${date}T00:00:00.000Z`, cashAccountId: kind === "cash" ? accountId : null, bankAccountId: kind === "bank" ? accountId : null, currencyCode: "TRY", description: description || null } };
}
export function parseBankTransfer(data: FormData): Result<BankTransferInput> { const fromBankAccountId = text(data, "fromBankAccountId"); const toBankAccountId = text(data, "toBankAccountId"); const amountRaw = text(data, "amount"); const amount = Number(amountRaw.replace(",", ".")); const date = text(data, "transactionDate"); const description = text(data, "description"); const idempotencyKey = text(data, "idempotencyKey"); const e: Record<string, string[]> = {}; if (!UUID.test(fromBankAccountId)) e.fromBankAccountId = ["Kaynak banka hesabını seçin."]; if (!UUID.test(toBankAccountId)) e.toBankAccountId = ["Hedef banka hesabını seçin."]; if (fromBankAccountId === toBankAccountId) e.toBankAccountId = ["Kaynak ve hedef banka farklı olmalıdır."]; if (!MONEY.test(amountRaw) || amount <= 0) e.amount = ["Tutar sıfırdan büyük ve en fazla 2 ondalıklı olmalıdır."]; if (!date || Number.isNaN(Date.parse(`${date}T00:00:00Z`))) e.transactionDate = ["Geçerli bir tarih girin."]; if (!UUID.test(idempotencyKey)) e.idempotencyKey = ["İşlem anahtarı geçersiz; sayfayı yenileyin."]; if (description.length > 500) e.description = ["Açıklama en fazla 500 karakter olabilir."]; return Object.keys(e).length ? fail(e) : { ok: true, idempotencyKey, input: { fromBankAccountId, toBankAccountId, amount, transactionDate: `${date}T00:00:00.000Z`, currencyCode: "TRY", description: description || null } }; }
