import type { ReportColumn, ReportDefinition, ReportGroup } from "./types";

// Burada kolon biçimlerini kısa ama tip güvenli kurucularla rapor tanımlarında görünür tutuyorum.
const text = (field: ReportColumn["field"], label: string): ReportColumn => ({ field, label, kind: "text" });
const date = (field: ReportColumn["field"], label: string): ReportColumn => ({ field, label, kind: "date" });
const money = (field: ReportColumn["field"], label: string): ReportColumn => ({ field, label, kind: "money", align: "right" });
const number = (field: ReportColumn["field"], label: string): ReportColumn => ({ field, label, kind: "number", align: "right" });
const percent = (field: ReportColumn["field"], label: string): ReportColumn => ({ field, label, kind: "percent", align: "right" });
const boolean = (field: ReportColumn["field"], label: string): ReportColumn => ({ field, label, kind: "boolean" });

// Burada her raporun finansal anlamını, filtresini ve kolon sözlüğünü diğer raporlardan bağımsız tanımlıyorum.
export const accountingReportCatalog: ReportDefinition[] = [
  { slug: "sales", title: "Satış raporu", shortTitle: "Satışlar", description: "Sipariş bazında satış, maliyet ve brüt kâr görünümü.", group: "Satış ve alış", endpoint: "/api/accounting/reports/sales", filters: { search: true, date: true, id: true, idLabel: "Satış / sipariş kimliği", invoiceStatus: true }, columns: [text("number", "Sipariş"), text("name", "Cari hesap"), date("date", "Satış tarihi"), date("dueDate", "Vade"), money("amount", "KDV dahil satış"), money("secondaryAmount", "Satış maliyeti"), money("tertiaryAmount", "Brüt kâr"), number("quantity", "Stok miktarı"), percent("rate", "Kâr marjı"), boolean("hasSalesInvoice", "Faturalı")] },
  { slug: "sales-detail", title: "Tekil satış raporu", shortTitle: "Satış detayı", description: "Belirli bir muhasebe satışının finansal özeti.", group: "Satış ve alış", endpoint: "/api/accounting/reports/sales/{scopeId}", scope: { label: "Satış kimliği", placeholder: "UUID" }, filters: {}, columns: [text("number", "Sipariş"), text("name", "Cari hesap"), date("date", "Satış tarihi"), date("dueDate", "Vade"), money("amount", "KDV dahil satış"), money("secondaryAmount", "Satış maliyeti"), money("tertiaryAmount", "Brüt kâr"), number("quantity", "Stok miktarı"), percent("rate", "Kâr marjı"), boolean("hasSalesInvoice", "Faturalı")] },
  { slug: "sales-items", title: "Satış kalemleri raporu", shortTitle: "Satış kalemleri", description: "Bir muhasebe satışının varyant bazlı gelir ve maliyet kalemleri.", group: "Satış ve alış", endpoint: "/api/accounting/reports/sales/{scopeId}/items", scope: { label: "Satış kimliği", placeholder: "UUID" }, filters: { search: true, date: true }, columns: [text("number", "Sipariş"), text("name", "Ürün / varyant"), date("date", "Satış tarihi"), money("amount", "Net satış"), money("secondaryAmount", "Satış maliyeti"), money("tertiaryAmount", "Brüt kâr"), number("quantity", "Stok miktarı"), percent("rate", "Kâr marjı"), boolean("hasSalesInvoice", "Faturalı")] },
  { slug: "sales-invoices", title: "Satış faturaları raporu", shortTitle: "Satış faturaları", description: "Satış faturalarının gelir, maliyet ve kârlılık özeti.", group: "Satış ve alış", endpoint: "/api/accounting/reports/sales-invoices", filters: { search: true, date: true, id: true, idLabel: "Fatura kimliği" }, columns: [text("number", "Fatura"), text("name", "Cari hesap"), date("date", "Fatura tarihi"), date("dueDate", "Vade"), money("amount", "KDV dahil satış"), money("secondaryAmount", "Satış maliyeti"), money("tertiaryAmount", "Brüt kâr"), number("quantity", "Stok miktarı"), percent("rate", "Kâr marjı")] },
  { slug: "sales-invoice-detail", title: "Tekil satış faturası raporu", shortTitle: "Satış faturası detayı", description: "Belirli bir satış faturasının finansal özeti.", group: "Satış ve alış", endpoint: "/api/accounting/reports/sales-invoices/{scopeId}", scope: { label: "Satış faturası kimliği", placeholder: "UUID" }, filters: {}, columns: [text("number", "Fatura"), text("name", "Cari hesap"), date("date", "Fatura tarihi"), date("dueDate", "Vade"), money("amount", "KDV dahil satış"), money("secondaryAmount", "Satış maliyeti"), money("tertiaryAmount", "Brüt kâr"), number("quantity", "Stok miktarı"), percent("rate", "Kâr marjı")] },
  { slug: "purchase-invoices", title: "Alış faturaları raporu", shortTitle: "Alış faturaları", description: "Tedarikçi belgeleri, dağıtılmış gider ve nihai maliyet görünümü.", group: "Satış ve alış", endpoint: "/api/accounting/reports/purchase-invoices", filters: { search: true, date: true, id: true, idLabel: "Alış faturası kimliği" }, columns: [text("number", "Fatura"), text("name", "Tedarikçi"), date("date", "Fatura tarihi"), date("dueDate", "Vade"), money("amount", "KDV dahil toplam"), money("secondaryAmount", "Dağıtılmış gider"), money("tertiaryAmount", "Nihai maliyet"), number("quantity", "Miktar"), text("currencyCode", "Para birimi")] },
  { slug: "purchase-invoice-detail", title: "Tekil alış faturası raporu", shortTitle: "Alış faturası detayı", description: "Belirli bir alış faturasının gider ve maliyet özeti.", group: "Satış ve alış", endpoint: "/api/accounting/reports/purchase-invoices/{scopeId}", scope: { label: "Alış faturası kimliği", placeholder: "UUID" }, filters: {}, columns: [text("number", "Fatura"), text("name", "Tedarikçi"), date("date", "Fatura tarihi"), date("dueDate", "Vade"), money("amount", "KDV dahil toplam"), money("secondaryAmount", "Dağıtılmış gider"), money("tertiaryAmount", "Nihai maliyet"), number("quantity", "Miktar"), text("currencyCode", "Para birimi")] },
  { slug: "uncosted-stock", title: "Maliyetsiz stok hareketleri", shortTitle: "Maliyetsiz hareketler", description: "FIFO maliyeti henüz oluşmamış stok çıkışları.", group: "Stok ve maliyet", endpoint: "/api/accounting/reports/stock-movements/uncosted", filters: { search: true, date: true, id: true, idLabel: "Varyant kimliği" }, columns: [date("date", "Hareket tarihi"), text("name", "Varyant"), text("number", "Hareket referansı"), number("quantity", "Eksik maliyet miktarı")] },
  { slug: "partially-costed-stock", title: "Kısmi maliyetli stok hareketleri", shortTitle: "Kısmi maliyetliler", description: "Maliyetinin yalnız bir bölümü FIFO ile karşılanan çıkışlar.", group: "Stok ve maliyet", endpoint: "/api/accounting/reports/stock-movements/partially-costed", filters: { search: true, date: true, id: true, idLabel: "Varyant kimliği" }, columns: [date("date", "Hareket tarihi"), text("name", "Varyant"), text("number", "Hareket referansı"), number("quantity", "Eksik maliyet miktarı")] },
  { slug: "cost-layers", title: "FIFO maliyet katmanları", shortTitle: "Maliyet katmanları", description: "Orijinal miktarları ve maliyetleriyle bütün FIFO katmanları.", group: "Stok ve maliyet", endpoint: "/api/accounting/reports/cost-layers", filters: { search: true, date: true, id: true, idLabel: "Varyant kimliği" }, columns: [date("date", "Maliyet tarihi"), text("name", "Varyant"), text("number", "Kaynak"), number("quantity", "Orijinal miktar"), money("secondaryAmount", "Birim maliyet"), money("tertiaryAmount", "Orijinal toplam maliyet"), money("amount", "Kalan değer")] },
  { slug: "remaining-cost-layers", title: "Kalan FIFO katmanları", shortTitle: "Kalan katmanlar", description: "Henüz tüketilmemiş FIFO miktarı ve stok değeri.", group: "Stok ve maliyet", endpoint: "/api/accounting/reports/cost-layers/remaining", filters: { search: true, date: true, id: true, idLabel: "Varyant kimliği" }, columns: [date("date", "Maliyet tarihi"), text("name", "Varyant"), text("number", "Kaynak"), number("quantity", "Kalan miktar"), money("secondaryAmount", "Birim maliyet"), money("amount", "Kalan değer")] },
  { slug: "cost-layer-consumptions", title: "FIFO tüketim kayıtları", shortTitle: "Katman tüketimleri", description: "Çıkışların hangi maliyet katmanlarını ne kadar tükettiği.", group: "Stok ve maliyet", endpoint: "/api/accounting/reports/cost-layer-consumptions", filters: { search: true, date: true, id: true, idLabel: "Maliyet katmanı kimliği" }, columns: [date("date", "Tüketim tarihi"), text("name", "Varyant"), text("number", "Çıkış referansı"), number("quantity", "Tüketilen miktar"), money("secondaryAmount", "Birim maliyet"), money("amount", "Toplam tüketim maliyeti")] },
  { slug: "variant-cost-history", title: "Varyant maliyet geçmişi raporu", shortTitle: "Maliyet geçmişi", description: "Varyant maliyetlerinin dönemsel değişim raporu.", group: "Stok ve maliyet", endpoint: "/api/accounting/reports/product-variant-cost-history", filters: { search: true, date: true, id: true, idLabel: "Varyant kimliği" }, columns: [date("date", "Geçerlilik başlangıcı"), date("dueDate", "Geçerlilik sonu"), text("name", "Varyant"), money("secondaryAmount", "Önceki maliyet"), money("amount", "Yeni KDV hariç maliyet"), money("tertiaryAmount", "Yeni KDV dahil maliyet"), number("quantity", "Açılış stoğu")] },
  { slug: "warehouse-valuation", title: "Depo stok değerleme", shortTitle: "Stok değerleme", description: "Varyantların kalan FIFO miktarı üzerinden depo değeri.", group: "Stok ve maliyet", endpoint: "/api/accounting/reports/warehouse-stock-valuation", filters: { search: true, date: true, id: true, idLabel: "Varyant kimliği" }, columns: [text("name", "Varyant"), text("number", "Depo"), date("date", "Son katman tarihi"), number("quantity", "Kalan miktar"), money("amount", "KDV hariç stok değeri")] },
  { slug: "product-profitability", title: "Ürün kârlılığı", shortTitle: "Ürün kârlılığı", description: "Ürün bazında net satış, FIFO maliyeti ve brüt kâr.", group: "Kârlılık", endpoint: "/api/accounting/reports/profitability/products", filters: { search: true, date: true }, columns: [text("number", "Ürün kodu"), text("name", "Ürün"), date("date", "Son satış"), number("quantity", "Satılan miktar"), money("amount", "Net satış"), money("secondaryAmount", "Satış maliyeti"), money("tertiaryAmount", "Brüt kâr"), percent("rate", "Kâr marjı")] },
  { slug: "variant-profitability", title: "Varyant kârlılığı", shortTitle: "Varyant kârlılığı", description: "Varyant bazında net satış, FIFO maliyeti ve brüt kâr.", group: "Kârlılık", endpoint: "/api/accounting/reports/profitability/product-variants", filters: { search: true, date: true, id: true, idLabel: "Varyant kimliği" }, columns: [text("number", "SKU"), text("name", "Varyant"), date("date", "Son satış"), number("quantity", "Satılan miktar"), money("amount", "Net satış"), money("secondaryAmount", "Satış maliyeti"), money("tertiaryAmount", "Brüt kâr"), percent("rate", "Kâr marjı")] },
  { slug: "sales-order-profitability", title: "Satış kârlılığı", shortTitle: "Sipariş kârlılığı", description: "Muhasebe satışı bazında maliyet ve brüt kâr.", group: "Kârlılık", endpoint: "/api/accounting/reports/profitability/sales-orders", filters: { search: true, date: true, id: true, idLabel: "Satış kimliği", invoiceStatus: true }, columns: [text("number", "Sipariş"), text("name", "Cari hesap"), date("date", "Satış tarihi"), number("quantity", "Miktar"), money("amount", "Net satış"), money("secondaryAmount", "Satış maliyeti"), money("tertiaryAmount", "Brüt kâr"), percent("rate", "Kâr marjı"), boolean("hasSalesInvoice", "Faturalı")] },
  { slug: "sales-invoice-profitability", title: "Fatura kârlılığı", shortTitle: "Fatura kârlılığı", description: "Satış faturası bazında maliyet ve brüt kâr.", group: "Kârlılık", endpoint: "/api/accounting/reports/profitability/sales-invoices", filters: { search: true, date: true, id: true, idLabel: "Satış faturası kimliği" }, columns: [text("number", "Fatura"), text("name", "Cari hesap"), date("date", "Fatura tarihi"), number("quantity", "Miktar"), money("amount", "Net satış"), money("secondaryAmount", "Satış maliyeti"), money("tertiaryAmount", "Brüt kâr"), percent("rate", "Kâr marjı")] },
  { slug: "current-account-statement", title: "Cari hesap ekstresi", shortTitle: "Cari ekstre", description: "Belirli bir carinin borç, alacak ve kalan hareketleri.", group: "Cari ve nakit", endpoint: "/api/accounting/reports/current-accounts/{scopeId}/statement", scope: { label: "Cari hesap kimliği", placeholder: "UUID" }, filters: { date: true }, columns: [date("date", "İşlem tarihi"), date("dueDate", "Vade"), text("number", "Belge / referans"), text("name", "Açıklama"), money("amount", "Borç"), money("secondaryAmount", "Alacak"), money("tertiaryAmount", "Kalan") ] },
  { slug: "receivables", title: "Alacaklar raporu", shortTitle: "Alacaklar", description: "Müşteri cari hesaplarındaki açık alacak kalemleri.", group: "Cari ve nakit", endpoint: "/api/accounting/reports/receivables", filters: { search: true, date: true, id: true, idLabel: "Cari hesap kimliği" }, columns: [text("name", "Cari hesap"), text("number", "Belge"), date("date", "İşlem tarihi"), date("dueDate", "Vade"), money("amount", "Borç"), money("secondaryAmount", "Tahsil edilen"), money("tertiaryAmount", "Kalan alacak")] },
  { slug: "debts", title: "Borçlar raporu", shortTitle: "Borçlar", description: "Tedarikçi cari hesaplarındaki açık borç kalemleri.", group: "Cari ve nakit", endpoint: "/api/accounting/reports/debts", filters: { search: true, date: true, id: true, idLabel: "Cari hesap kimliği" }, columns: [text("name", "Cari hesap"), text("number", "Belge"), date("date", "İşlem tarihi"), date("dueDate", "Vade"), money("secondaryAmount", "Borç"), money("amount", "Ödenen"), money("tertiaryAmount", "Kalan borç")] },
  { slug: "overdue-receivables", title: "Gecikmiş alacaklar", shortTitle: "Gecikmiş alacaklar", description: "Vadesi geçmiş açık müşteri alacakları.", group: "Cari ve nakit", endpoint: "/api/accounting/reports/overdue-receivables", filters: { search: true, date: true, id: true, idLabel: "Cari hesap kimliği" }, columns: [text("name", "Cari hesap"), text("number", "Belge"), date("date", "İşlem tarihi"), date("dueDate", "Vade"), money("tertiaryAmount", "Geciken alacak")] },
  { slug: "overdue-debts", title: "Gecikmiş borçlar", shortTitle: "Gecikmiş borçlar", description: "Vadesi geçmiş açık tedarikçi borçları.", group: "Cari ve nakit", endpoint: "/api/accounting/reports/overdue-debts", filters: { search: true, date: true, id: true, idLabel: "Cari hesap kimliği" }, columns: [text("name", "Cari hesap"), text("number", "Belge"), date("date", "İşlem tarihi"), date("dueDate", "Vade"), money("tertiaryAmount", "Geciken borç")] },
  { slug: "payments-collections", title: "Ödeme ve tahsilat raporu", shortTitle: "Ödeme ve tahsilatlar", description: "Ödemelerin dağıtılan ve dağıtılmayan tutarları.", group: "Cari ve nakit", endpoint: "/api/accounting/reports/payments-and-collections", filters: { search: true, date: true, id: true, idLabel: "Cari hesap kimliği" }, columns: [date("date", "Ödeme tarihi"), text("name", "Cari hesap"), text("number", "Referans"), money("amount", "İşlem tutarı"), money("secondaryAmount", "Dağıtılan"), money("tertiaryAmount", "Dağıtılmayan"), text("currencyCode", "Para birimi")] },
  { slug: "cash-movements", title: "Kasa hareketleri raporu", shortTitle: "Kasa hareketleri", description: "Kasa hesaplarındaki giriş ve çıkışların işaretli tutarları.", group: "Cari ve nakit", endpoint: "/api/accounting/reports/cash-movements", filters: { search: true, date: true, id: true, idLabel: "Kasa hesabı kimliği" }, columns: [date("date", "İşlem tarihi"), text("name", "Kasa hesabı"), text("number", "Referans"), text("relatedId", "Bağlı cari"), money("amount", "İşaretli tutar"), money("secondaryAmount", "Mutlak tutar"), text("currencyCode", "Para birimi")] },
  { slug: "bank-movements", title: "Banka hareketleri raporu", shortTitle: "Banka hareketleri", description: "Banka hesaplarındaki giriş ve çıkışların işaretli tutarları.", group: "Cari ve nakit", endpoint: "/api/accounting/reports/bank-movements", filters: { search: true, date: true, id: true, idLabel: "Banka hesabı kimliği" }, columns: [date("date", "İşlem tarihi"), text("name", "Banka hesabı"), text("number", "Referans"), text("relatedId", "Bağlı cari"), money("amount", "İşaretli tutar"), money("secondaryAmount", "Mutlak tutar"), text("currencyCode", "Para birimi")] },
  { slug: "purchase-vat", title: "Alış KDV raporu", shortTitle: "Alış KDV", description: "Alış satırlarının KDV oranına göre matrah ve vergi özeti.", group: "Vergi", endpoint: "/api/accounting/reports/vat/purchases", filters: { date: true }, columns: [percent("rate", "KDV oranı"), money("amount", "KDV hariç matrah"), money("secondaryAmount", "KDV tutarı"), money("tertiaryAmount", "KDV dahil toplam"), number("quantity", "Satır sayısı")] },
  { slug: "sales-vat", title: "Satış KDV raporu", shortTitle: "Satış KDV", description: "Satış satırlarının KDV oranına göre matrah ve vergi özeti.", group: "Vergi", endpoint: "/api/accounting/reports/vat/sales", filters: { date: true }, columns: [percent("rate", "KDV oranı"), money("amount", "KDV hariç matrah"), money("secondaryAmount", "KDV tutarı"), money("tertiaryAmount", "KDV dahil toplam"), number("quantity", "Satır sayısı")] },
];

// Burada katalog sırasını yöneticinin finansal inceleme akışına göre sabitliyorum.
export const accountingReportGroups: ReportGroup[] = ["Satış ve alış", "Stok ve maliyet", "Kârlılık", "Cari ve nakit", "Vergi"];

// Burada URL slug'ını yalnız yayımlanmış rapor allowlist'i içinde çözüyorum.
export function getAccountingReport(slug: string): ReportDefinition | undefined {
  return accountingReportCatalog.find((report) => report.slug === slug);
}
