using ECommerce.Domain.Common;

namespace ECommerce.Domain.Entities;

public sealed class ProductImage : AuditableEntity
{
    public long ProductId { get; private set; }
    public Product Product { get; private set; } = null!;
    public string ImageUrl { get; private set; } = null!;
    public string? AltText { get; private set; }
    public bool IsAltTextAutoGenerated { get; private set; }
    public int DisplayOrder { get; private set; }
    public bool IsMain { get; private set; }
    public Guid ConcurrencyToken { get; private set; }

    private ProductImage()
    {
    }

    public ProductImage(
        long productId,
        string imageUrl,
        int displayOrder = 0,
        bool isMain = false,
        string? altText = null,
        bool isAltTextAutoGenerated = false)
    {
        if (productId <= 0)
        {
            throw new DomainException("Product id is required.");
        }

        ProductId = productId;
        SetImageUrl(imageUrl);
        SetDisplayOrder(displayOrder);
        SetAltText(altText, isAltTextAutoGenerated);
        IsMain = isMain;
        ConcurrencyToken = Guid.NewGuid();
    }

    public ProductImage(Product product, string imageUrl, int displayOrder = 0, bool isMain = false, string? altText = null)
        : this(
            1,
            imageUrl,
            displayOrder,
            isMain,
            string.IsNullOrWhiteSpace(altText) ? product?.Title : altText,
            string.IsNullOrWhiteSpace(altText))
    {
        Product = product ?? throw new DomainException("Product cannot be empty.");
        ProductId = product.Id;
    }

    public void Update(
        string imageUrl,
        string? altText,
        int displayOrder,
        bool isMain,
        bool isAltTextAutoGenerated = false)
    {
        SetImageUrl(imageUrl);
        SetDisplayOrder(displayOrder);
        SetAltText(altText, isAltTextAutoGenerated);
        IsMain = isMain;
        ConcurrencyToken = Guid.NewGuid();
        MarkAsUpdated();
    }

    public void UnsetAsMain()
    {
        if (!IsMain)
        {
            return;
        }

        IsMain = false;
        ConcurrencyToken = Guid.NewGuid();
        MarkAsUpdated();
    }

    public void ApplyAutomaticAltText(string productTitle)
    {
        SetAltText(productTitle, true);
        ConcurrencyToken = Guid.NewGuid();
        MarkAsUpdated();
    }

    private void SetImageUrl(string imageUrl)
    {
        if (string.IsNullOrWhiteSpace(imageUrl))
        {
            throw new DomainException("Image url cannot be empty.");
        }

        ImageUrl = imageUrl.Trim();
    }

    private void SetDisplayOrder(int displayOrder)
    {
        if (displayOrder < 0)
        {
            throw new DomainException("Display order cannot be negative.");
        }

        DisplayOrder = displayOrder;
    }

    private void SetAltText(string? altText, bool isAutoGenerated)
    {
        if (string.IsNullOrWhiteSpace(altText))
        {
            if (isAutoGenerated)
            {
                throw new DomainException("Automatic image alt text cannot be empty.");
            }

            AltText = null;
            IsAltTextAutoGenerated = false;
            return;
        }

        AltText = altText.Trim();
        IsAltTextAutoGenerated = isAutoGenerated;
    }
}
