import { describe, expect, it } from "vitest";
import { parsePaymentForm } from "./form-data";
const accountId = "11111111-1111-4111-8111-111111111111"; const cashId = "22222222-2222-4222-8222-222222222222"; const targetA = "33333333-3333-4333-8333-333333333333"; const targetB = "44444444-4444-4444-8444-444444444444";
function paymentForm(type: 1 | 2, amount = "100.00"): FormData { const data = new FormData(); data.set("idempotencyKey", "payment_intent_1"); data.set("currentAccountId", accountId); data.set("type", String(type)); data.set("amount", amount); data.set("paymentDate", "2026-08-24"); data.set("accountChoice", `cash:${cashId}`); return data; }
function allocate(data: FormData, id: string, amount: string) { data.append("allocationId", id); data.set(`allocation:${id}`, amount); }
describe("payment form contract", () => {
  it("requires collection allocation and exact cent equality", () => { expect(parsePaymentForm(paymentForm(1))).toMatchObject({ ok: false, state: { fieldErrors: { allocations: expect.any(Array) } } }); const data = paymentForm(1); allocate(data, targetA, "99.99"); expect(parsePaymentForm(data)).toMatchObject({ ok: false, state: { fieldErrors: { allocations: expect.any(Array) } } }); });
  it("maps a fully allocated collection with exactly one cash account", () => { const data = paymentForm(1); allocate(data, targetA, "40.10"); allocate(data, targetB, "59.90"); const result = parsePaymentForm(data); expect(result.ok).toBe(true); if (!result.ok) return; expect(result.input).toMatchObject({ type: 1, amount: 100, cashAccountId: cashId, bankAccountId: null, currencyCode: "TRY", exchangeRate: 1, allocations: [{ currentAccountTransactionId: targetA, amount: 40.1 }, { currentAccountTransactionId: targetB, amount: 59.9 }] }); });
  it("allows only a wholly unallocated supplier advance or an exact distribution", () => { expect(parsePaymentForm(paymentForm(2))).toMatchObject({ ok: true, input: { allocations: [] } }); const data = paymentForm(2); allocate(data, targetA, "20"); expect(parsePaymentForm(data)).toMatchObject({ ok: false, state: { fieldErrors: { allocations: expect.any(Array) } } }); });
  it("rejects sub-cent and decimal overflow values", () => { expect(parsePaymentForm(paymentForm(2, "10.001"))).toMatchObject({ ok: false, state: { fieldErrors: { amount: expect.any(Array) } } }); expect(parsePaymentForm(paymentForm(2, "12345678901234567.89"))).toMatchObject({ ok: false, state: { fieldErrors: { amount: expect.any(Array) } } }); });
  it("rejects repeated targets and preserves the intent draft", () => { const data = paymentForm(1); allocate(data, targetA, "50"); data.append("allocationId", targetA); expect(parsePaymentForm(data)).toMatchObject({ ok: false, state: { fieldErrors: { allocations: expect.any(Array) }, draft: { idempotencyKey: "payment_intent_1" } } }); });
});
