import Link from "next/link";
import { AdminPagination } from "@/modules/admin-shell/components/admin-pagination";
import { formatAccountingDate, formatAccountingMoney } from "@/modules/accounting/core/presentation";
import { documentStatusClass, documentStatusLabel } from "../presentation";
import { buildSalesInvoiceListHref, buildSalesOrderListHref } from "../query";
import type { AccountingSalesOrderPage, SalesInvoicePage, SalesListQuery } from "../types";

export function SalesOrderRegister({ page, query }: { page: AccountingSalesOrderPage; query: SalesListQuery }) {
  return <section aria-label="Muhasebe satışları sicili" className="overflow-hidden rounded-xl border border-border bg-surface">
    {page.items.length ? <div role="region" aria-label="Muhasebe satışları; yatay kaydırılabilir" tabIndex={0} className="overflow-x-auto outline-none focus:ring-2 focus:ring-inset focus:ring-focus/30"><table className="w-full min-w-[940px] text-left text-sm"><thead className="border-b border-border bg-surface-subtle/80 text-[11px] font-bold uppercase tracking-[0.08em] text-muted"><tr><th className="sticky left-0 z-10 w-56 bg-surface-subtle px-4 py-2.5">Belge</th><th className="px-3 py-2.5">Müşteri</th><th className="px-3 py-2.5">Satış tarihi</th><th className="px-3 py-2.5">Durum</th><th className="px-3 py-2.5">Fatura bağı</th><th className="px-4 py-2.5 text-right">Genel toplam</th></tr></thead><tbody className="divide-y divide-border/80">{page.items.map((order) => <tr key={order.id} className="hover:bg-primary-soft/20"><td className="sticky left-0 bg-surface px-4 py-3"><Link href={`/accounting/sales-orders/${encodeURIComponent(order.id)}`} className="font-semibold hover:text-primary">{order.orderNumber}</Link><span className="mt-0.5 block font-mono text-[11px] text-muted">{order.id.slice(0, 8)}</span></td><td className="max-w-xs px-3 py-3"><Link href={`/accounting/current-accounts/${encodeURIComponent(order.currentAccountId)}`} className="font-medium hover:text-primary">{order.currentAccountName}</Link></td><td className="px-3 py-3 text-muted">{formatAccountingDate(order.orderDate)}</td><td className="px-3 py-3"><span className={`inline-flex rounded-md border px-2 py-0.5 text-xs font-bold ${documentStatusClass(order.status)}`}>{documentStatusLabel(order.status)}</span></td><td className="px-3 py-3">{order.salesInvoiceId ? <Link href={`/accounting/sales-invoices/${encodeURIComponent(order.salesInvoiceId)}`} className="font-semibold text-primary hover:text-primary-hover">Faturayı aç →</Link> : <span className="text-muted">Faturasız</span>}</td><td className="px-4 py-3 text-right font-semibold tabular-nums">{formatAccountingMoney(order.grandTotalIncludingVat, "TRY")}</td></tr>)}</tbody></table></div> : <Empty title="Henüz muhasebe satışı bulunmuyor" description="Müşteri carisine bağlı ilk satış taslağını oluşturarak başlayın." />}
    <AdminPagination action="/accounting/sales-orders" ariaLabel="Muhasebe satışları sayfalama" buildHref={(number) => buildSalesOrderListHref(query, number)} itemLabel="muhasebe satışı" pageNumber={page.pageNumber} pageSize={page.pageSize} totalCount={page.totalCount} totalPages={page.totalPages} />
  </section>;
}

export function SalesInvoiceRegister({ page, query }: { page: SalesInvoicePage; query: SalesListQuery }) {
  return <section aria-label="Satış faturaları sicili" className="overflow-hidden rounded-xl border border-border bg-surface">
    {page.items.length ? <div role="region" aria-label="Satış faturaları; yatay kaydırılabilir" tabIndex={0} className="overflow-x-auto outline-none focus:ring-2 focus:ring-inset focus:ring-focus/30"><table className="w-full min-w-[940px] text-left text-sm"><thead className="border-b border-border bg-surface-subtle/80 text-[11px] font-bold uppercase tracking-[0.08em] text-muted"><tr><th className="sticky left-0 z-10 w-56 bg-surface-subtle px-4 py-2.5">Fatura</th><th className="px-3 py-2.5">Müşteri</th><th className="px-3 py-2.5">Fatura tarihi</th><th className="px-3 py-2.5">Durum</th><th className="px-3 py-2.5">Muhasebe satışı</th><th className="px-4 py-2.5 text-right">Genel toplam</th></tr></thead><tbody className="divide-y divide-border/80">{page.items.map((invoice) => <tr key={invoice.id} className="hover:bg-primary-soft/20"><td className="sticky left-0 bg-surface px-4 py-3"><Link href={`/accounting/sales-invoices/${encodeURIComponent(invoice.id)}`} className="font-semibold hover:text-primary">{invoice.invoiceNumber}</Link><span className="mt-0.5 block font-mono text-[11px] text-muted">{invoice.id.slice(0, 8)}</span></td><td className="max-w-xs px-3 py-3"><Link href={`/accounting/current-accounts/${encodeURIComponent(invoice.currentAccountId)}`} className="font-medium hover:text-primary">{invoice.currentAccountName}</Link></td><td className="px-3 py-3 text-muted">{formatAccountingDate(invoice.invoiceDate)}</td><td className="px-3 py-3"><span className={`inline-flex rounded-md border px-2 py-0.5 text-xs font-bold ${documentStatusClass(invoice.status)}`}>{documentStatusLabel(invoice.status)}</span></td><td className="px-3 py-3"><Link href={`/accounting/sales-orders/${encodeURIComponent(invoice.accountingSalesOrderId)}`} className="font-semibold text-primary hover:text-primary-hover">Satışı aç →</Link></td><td className="px-4 py-3 text-right font-semibold tabular-nums">{formatAccountingMoney(invoice.grandTotalIncludingVat, "TRY")}</td></tr>)}</tbody></table></div> : <Empty title="Henüz satış faturası bulunmuyor" description="Yeni bir satışla birlikte fatura oluşturabilir veya mevcut muhasebe satışını faturalayabilirsiniz." />}
    <AdminPagination action="/accounting/sales-invoices" ariaLabel="Satış faturaları sayfalama" buildHref={(number) => buildSalesInvoiceListHref(query, number)} itemLabel="satış faturası" pageNumber={page.pageNumber} pageSize={page.pageSize} totalCount={page.totalCount} totalPages={page.totalPages} />
  </section>;
}

function Empty({ title, description }: { title: string; description: string }) { return <div className="px-5 py-14 text-center"><h2 className="text-base font-semibold">{title}</h2><p className="mt-2 text-sm text-muted">{description}</p></div>; }
