import Link from "next/link";
/* eslint-disable react/no-unescaped-entities */
import { formatAccountingDate, formatAccountingMoney } from "@/modules/accounting/core/presentation";
import { discountTypeLabel, documentStatusClass, documentStatusLabel, shippingPayerLabel } from "../presentation";
import type { AccountingSalesOrder, SalesInvoice } from "../types";
import { InvoiceFromOrderForm } from "./invoice-from-order-form";
import { SalesInvoiceLifecycleActions, SalesOrderLifecycleActions } from "./sales-lifecycle-actions";

type SalesLine = AccountingSalesOrder["items"][number] | SalesInvoice["lines"][number];

export function SalesOrderDetail({ order }: { order: AccountingSalesOrder }) {
  return <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_21rem]"><div className="min-w-0 space-y-4"><DocumentFacts document={order} kind="order" /><SalesLines lines={order.items} status={order.status} currency={order.currencyCode} showStock /><AccountingEffects lines={order.items} currency={order.currencyCode} /></div><aside className="space-y-4 xl:sticky xl:top-20"><LifecycleCard status={order.status} createdAt={order.createdAt} updatedAt={order.updatedAt} postedAt={order.postedAt} cancelledAt={order.cancelledAt} cancellationReason={order.cancellationReason} /><FinancialSummary document={order} /><section className="rounded-xl border border-border bg-surface p-4"><h2 className="text-sm font-semibold">Belge ilişkileri</h2>{order.salesInvoiceId ? <Link href={`/accounting/sales-invoices/${encodeURIComponent(order.salesInvoiceId)}`} className="mt-3 inline-flex min-h-9 items-center text-sm font-semibold text-primary hover:text-primary-hover">Bağlı faturayı aç →</Link> : <p className="mt-2 text-sm text-muted">Bu satışa henüz iç fatura bağlanmadı.</p>}</section><section className="rounded-xl border border-border bg-surface p-4"><h2 className="text-sm font-semibold">Lifecycle işlemleri</h2><p className="mt-1 text-xs leading-5 text-muted">Taslak düzenlenir/post edilir; yalnız post edilmiş satış iptal edilebilir.</p><div className="mt-3"><SalesOrderLifecycleActions orderId={order.id} orderNumber={order.orderNumber} invoiceId={order.salesInvoiceId} status={order.status} /></div></section>{!order.salesInvoiceId && order.status !== 3 ? <InvoiceFromOrderForm orderId={order.id} orderNumber={order.orderNumber} status={order.status} /> : null}</aside></div>;
}

export function SalesInvoiceDetail({ invoice }: { invoice: SalesInvoice }) {
  return <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_21rem]"><div className="min-w-0 space-y-4"><section className="rounded-xl border border-primary/30 bg-primary-soft/25 p-4 sm:flex sm:items-center sm:justify-between sm:gap-4"><div><h2 className="text-sm font-semibold">Bağlı muhasebe satışı</h2><p className="mt-1 text-sm text-muted">Stok çıkışı, FIFO ve müşteri alacağı bu satışın tek etkisidir.</p></div><Link href={`/accounting/sales-orders/${encodeURIComponent(invoice.accountingSalesOrderId)}`} className="mt-3 inline-flex min-h-10 shrink-0 items-center rounded-lg border border-primary/30 bg-surface px-3 text-sm font-semibold text-primary hover:bg-primary-soft sm:mt-0">Muhasebe satışını aç →</Link></section><DocumentFacts document={invoice} kind="invoice" /><SalesLines lines={invoice.lines} status={invoice.status} currency={invoice.currencyCode} /><AccountingEffects lines={invoice.lines} currency={invoice.currencyCode} /></div><aside className="space-y-4 xl:sticky xl:top-20"><LifecycleCard status={invoice.status} createdAt={invoice.createdAt} postedAt={invoice.postedAt} cancelledAt={invoice.cancelledAt} cancellationReason={invoice.cancellationReason} /><FinancialSummary document={invoice} /><section className="rounded-xl border border-border bg-surface p-4"><h2 className="text-sm font-semibold">Lifecycle işlemleri</h2><p className="mt-1 text-xs leading-5 text-muted">Fatura post işlemi bağlı satışı post eder; ayrı bir finansal etki üretmez.</p><div className="mt-3"><SalesInvoiceLifecycleActions invoiceId={invoice.id} invoiceNumber={invoice.invoiceNumber} orderId={invoice.accountingSalesOrderId} status={invoice.status} /></div>{invoice.status === 2 ? <Link href={`/accounting/sales-orders/${encodeURIComponent(invoice.accountingSalesOrderId)}`} className="mt-3 inline-flex min-h-9 items-center text-xs font-semibold text-danger hover:underline">İptal için bağlı satışa git →</Link> : null}</section></aside></div>;
}

function DocumentFacts({ document, kind }: { document: AccountingSalesOrder | SalesInvoice; kind: "order" | "invoice" }) {
  const number = kind === "order" ? (document as AccountingSalesOrder).orderNumber : (document as SalesInvoice).invoiceNumber;
  const date = kind === "order" ? (document as AccountingSalesOrder).orderDate : (document as SalesInvoice).invoiceDate;
  return <section className="rounded-xl border border-border bg-surface p-4 sm:p-5"><div className="border-b border-border pb-4"><h2 className="text-base font-semibold">Belge ve müşteri</h2><p className="mt-1 text-sm text-muted">Cari snapshot, ticari koşullar ve API tarafından hesaplanan belge başlığı.</p></div><dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Fact label={kind === "order" ? "Satış numarası" : "Fatura numarası"} value={number} /><Fact label="Müşteri" value={document.currentAccountName} href={`/accounting/current-accounts/${encodeURIComponent(document.currentAccountId)}`} /><Fact label="Belge tarihi" value={formatAccountingDate(date)} /><Fact label="Vade tarihi" value={formatAccountingDate(document.dueDate)} /><Fact label="Vergi numarası" value={document.taxNumberSnapshot || "—"} /><Fact label="Vergi dairesi" value={document.taxOfficeSnapshot || "—"} /><Fact label="Kargo" value={`${formatAccountingMoney(document.shippingTotal, document.currencyCode)} · ${shippingPayerLabel(document.shippingPayer)}`} /><Fact label="Fatura indirimi" value={discountTypeLabel(document.invoiceDiscountType)} /><Fact label="Para birimi" value={`${document.currencyCode} · Kur ${document.exchangeRate}`} /><div className="sm:col-span-2 lg:col-span-3"><dt className="text-xs font-semibold text-muted">Adres snapshot</dt><dd className="mt-1 text-sm leading-6">{document.addressSnapshot || "—"}</dd></div>{document.description ? <div className="sm:col-span-2 lg:col-span-3"><dt className="text-xs font-semibold text-muted">Açıklama</dt><dd className="mt-1 text-sm leading-6">{document.description}</dd></div> : null}</dl></section>;
}

function SalesLines({ lines, status, currency, showStock = false }: { lines: SalesLine[]; status: number; currency: string; showStock?: boolean }) {
  return <section className="overflow-hidden rounded-xl border border-border bg-surface"><div className="border-b border-border px-4 py-4 sm:px-5"><h2 className="text-base font-semibold">Satış satırları</h2><p className="mt-1 text-sm text-muted">Ürün snapshot'ı, satış tutarları ve {status === 1 ? "post sonrası hesaplanacak" : "gerçekleşmiş"} maliyet/kâr.</p></div><div role="region" aria-label="Satış belgesi satırları; yatay kaydırılabilir" tabIndex={0} className="overflow-x-auto outline-none focus:ring-2 focus:ring-inset focus:ring-focus/30"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="border-b border-border bg-surface-subtle/80 text-[11px] font-bold uppercase tracking-[0.07em] text-muted"><tr><th className="px-4 py-2.5">Satır / ürün</th><th className="px-3 py-2.5 text-right">Satış / stok</th><th className="px-3 py-2.5 text-right">Birim fiyat</th><th className="px-3 py-2.5 text-right">İndirim</th><th className="px-3 py-2.5 text-right">Net</th><th className="px-3 py-2.5 text-right">KDV</th><th className="px-3 py-2.5 text-right">Toplam</th><th className="px-4 py-2.5 text-right">Maliyet / kâr</th></tr></thead><tbody className="divide-y divide-border">{lines.map((line) => <tr key={line.id}><td className="px-4 py-3"><p className="font-semibold">{line.lineNumber}. {line.productName}</p><p className="mt-0.5 text-xs text-muted">{line.variantName} · {line.sku}</p>{showStock && "stockMovements" in line ? <p className="mt-1 text-xs text-muted">{line.stockMovements.length} stok hareketi bağı</p> : null}</td><td className="px-3 py-3 text-right tabular-nums">{line.quantity} {line.unitOfMeasure}<span className="block text-xs text-muted">{line.stockQuantity} stok</span></td><td className="px-3 py-3 text-right tabular-nums">{formatAccountingMoney(line.enteredUnitPrice, currency)}<span className="block text-xs text-muted">{line.priceEntryMode === 1 ? "KDV hariç" : "KDV dahil"}</span></td><td className="px-3 py-3 text-right tabular-nums">{formatAccountingMoney(line.totalDiscountAmountIncludingVat, currency)}<span className="block text-xs text-muted">{discountTypeLabel(line.lineDiscountType)}</span></td><td className="px-3 py-3 text-right tabular-nums">{formatAccountingMoney(line.netAmountExcludingVat, currency)}</td><td className="px-3 py-3 text-right tabular-nums">{formatAccountingMoney(line.vatAmount, currency)}<span className="block text-xs text-muted">%{line.vatRate}</span></td><td className="px-3 py-3 text-right font-semibold tabular-nums">{formatAccountingMoney(line.totalAmountIncludingVat, currency)}</td><td className="px-4 py-3 text-right tabular-nums">{status === 1 ? <span className="text-muted">Post sonrası</span> : <>{formatAccountingMoney(line.costOfGoodsSold, currency)}<span className="block text-xs text-muted">Kâr {formatAccountingMoney(line.grossProfitExcludingVat, currency)} · %{line.grossProfitMargin.toFixed(2)}</span></>}</td></tr>)}</tbody></table></div></section>;
}

function AccountingEffects({ lines, currency }: { lines: SalesLine[]; currency: string }) {
  const consumptions = lines.flatMap((line) => line.costLayerConsumptions.map((item) => ({ ...item, lineNumber: line.lineNumber, productName: line.productName })));
  const movements = lines.flatMap((line) => "stockMovements" in line ? line.stockMovements.map((item) => ({ ...item, lineNumber: line.lineNumber, productName: line.productName })) : []);
  if (!consumptions.length && !movements.length) return <section className="rounded-xl border border-border bg-surface p-5"><h2 className="text-base font-semibold">Stok ve FIFO etkisi</h2><p className="mt-2 text-sm text-muted">Bu taslak henüz stok hareketi veya FIFO tüketimi üretmedi.</p></section>;
  return <section className="overflow-hidden rounded-xl border border-border bg-surface"><div className="border-b border-border px-4 py-4 sm:px-5"><h2 className="text-base font-semibold">Stok ve FIFO denetim izi</h2><p className="mt-1 text-sm text-muted">API'nin belge satırına bağladığı hareket ve maliyet tüketimleri. İptalde reversal ayrıntısı ayrıca projekte edilmediği için orijinal kayıtlar tarihsel olarak gösterilir.</p></div><div className="grid gap-px bg-border lg:grid-cols-2"><div className="bg-surface p-4"><h3 className="text-sm font-semibold">Stok hareketleri</h3>{movements.length ? <ul className="mt-3 space-y-2">{movements.map((item) => <li key={item.id} className="rounded-lg bg-surface-subtle p-3 text-xs"><span className="font-semibold">{item.lineNumber}. {item.productName}</span><span className="mt-1 block text-muted">Miktar {item.quantity} · Hareket {item.stockMovementId.slice(0, 8)}</span></li>)}</ul> : <p className="mt-3 text-xs leading-5 text-muted">Fatura DTO'su stok hareketlerini taşımaz; bağlı muhasebe satışından görüntülenir.</p>}</div><div className="bg-surface p-4"><h3 className="text-sm font-semibold">FIFO tüketimleri</h3>{consumptions.length ? <ul className="mt-3 space-y-2">{consumptions.map((item) => <li key={item.id} className="rounded-lg bg-surface-subtle p-3 text-xs"><span className="font-semibold">{item.lineNumber}. {item.productName}</span><span className="mt-1 block text-muted">{item.quantity} stok · {formatAccountingMoney(item.unitCostExcludingVat, currency)} / birim · {formatAccountingMoney(item.totalCostExcludingVat, currency)}</span></li>)}</ul> : <p className="mt-3 text-xs text-muted">Henüz FIFO tüketimi yok.</p>}</div></div></section>;
}

function LifecycleCard({ status, createdAt, updatedAt, postedAt, cancelledAt, cancellationReason }: { status: number; createdAt: string; updatedAt?: string | null; postedAt?: string | null; cancelledAt?: string | null; cancellationReason?: string | null }) { return <section className="rounded-xl border border-border bg-surface p-4"><div className="flex items-center justify-between gap-3"><h2 className="text-sm font-semibold">Belge durumu</h2><span className={`rounded-md border px-2 py-0.5 text-xs font-bold ${documentStatusClass(status)}`}>{documentStatusLabel(status)}</span></div><dl className="mt-4 space-y-3 text-xs"><RailFact label="Oluşturuldu" value={formatAccountingDate(createdAt)} />{updatedAt ? <RailFact label="Güncellendi" value={formatAccountingDate(updatedAt)} /> : null}<RailFact label="Post tarihi" value={formatAccountingDate(postedAt)} />{cancelledAt ? <RailFact label="İptal tarihi" value={formatAccountingDate(cancelledAt)} /> : null}</dl>{cancellationReason ? <p className="mt-3 rounded-lg border border-red-200 bg-red-50 p-2 text-xs leading-5 text-red-950"><strong>İptal gerekçesi:</strong> {cancellationReason}</p> : null}</section>; }

function FinancialSummary({ document }: { document: AccountingSalesOrder | SalesInvoice }) { return <section className="rounded-xl border border-border bg-surface p-4"><h2 className="text-sm font-semibold">API mali özeti</h2><dl className="mt-3 space-y-2 text-sm"><MoneyFact label="Ara toplam (KDV hariç)" value={document.subtotalExcludingVat} currency={document.currencyCode} /><MoneyFact label="Toplam indirim" value={document.totalDiscountExcludingVat} currency={document.currencyCode} /><MoneyFact label="Net tutar" value={document.netAmountExcludingVat} currency={document.currencyCode} /><MoneyFact label="KDV" value={document.vatTotal} currency={document.currencyCode} /><MoneyFact label="Genel toplam" value={document.grandTotalIncludingVat} currency={document.currencyCode} strong /><div className="my-3 border-t border-border" /><MoneyFact label="Ödenen" value={document.paidAmount} currency={document.currencyCode} /><MoneyFact label={document.status === 3 ? "Tarihsel kalan" : "Kalan müşteri alacağı"} value={document.remainingAmount} currency={document.currencyCode} strong /><MoneyFact label={document.status === 1 ? "Post sonrası maliyet" : "Satılan malın maliyeti"} value={document.totalCostOfGoodsSold} currency={document.currencyCode} /><MoneyFact label={document.status === 1 ? "Post sonrası brüt kâr" : "Brüt kâr"} value={document.grossProfitExcludingVat} currency={document.currencyCode} strong /></dl></section>; }
function Fact({ label, value, href }: { label: string; value: string; href?: string }) { return <div><dt className="text-xs font-semibold text-muted">{label}</dt><dd className="mt-1 text-sm font-medium">{href ? <Link href={href} className="text-primary hover:text-primary-hover">{value}</Link> : value}</dd></div>; }
function RailFact({ label, value }: { label: string; value: string }) { return <div className="flex items-start justify-between gap-3"><dt className="text-muted">{label}</dt><dd className="text-right font-medium">{value}</dd></div>; }
function MoneyFact({ label, value, currency, strong }: { label: string; value: number; currency: string; strong?: boolean }) { return <div className="flex items-start justify-between gap-3"><dt className="text-muted">{label}</dt><dd className={`text-right tabular-nums ${strong ? "font-bold text-foreground" : "font-medium"}`}>{formatAccountingMoney(value, currency)}</dd></div>; }
