import { formatDate, formatMoney, financialTypeLabel, isSafelyReversible, sourceTypeLabel } from "../presentation";
import type { FinancialTransaction } from "../types";
import { TransactionLifecycleAction } from "./transaction-lifecycle-action";

export function FinancialStatement({ transactions, accountPath }: { transactions: FinancialTransaction[]; accountPath: string }) {
  if (!transactions.length) return <section className="rounded-xl border border-dashed border-border-strong bg-surface p-8 text-center"><h2 className="text-lg font-semibold">Henüz finans hareketi yok</h2><p className="mt-2 text-sm text-muted">Bakiye sıfırdır ve hareket oluşturuldukça API tarafından hesaplanır.</p></section>;
  const reversedIds = new Set(transactions.flatMap((item) => item.reversesTransactionId ? [item.reversesTransactionId] : []));
  return <section className="overflow-hidden rounded-xl border border-border bg-surface" aria-label="Finans hesabı ekstresi"><p className="border-b border-border px-4 py-2 text-xs text-muted sm:hidden">Tüm ekstre kolonları için tabloyu yatay kaydırın.</p><div className="overflow-x-auto outline-none focus:ring-2 focus:ring-primary/30" tabIndex={0} role="region" aria-label="Kaydırılabilir finans ekstresi"><table className="min-w-[980px] w-full text-left text-sm"><thead className="bg-surface-subtle text-xs uppercase text-muted"><tr><th scope="col" className="px-4 py-3">Tarih</th><th scope="col" className="px-4 py-3">Hareket</th><th scope="col" className="px-4 py-3">Kaynak</th><th scope="col" className="px-4 py-3">Yön</th><th scope="col" className="px-4 py-3 text-right">Tutar</th><th scope="col" className="px-4 py-3 text-right">Hareket sonrası bakiye</th><th scope="col" className="px-4 py-3">İşlem</th></tr></thead><tbody className="divide-y divide-border">{transactions.map((tx) => <tr key={tx.id}><td className="px-4 py-3">{formatDate(tx.transactionDate)}</td><td className="px-4 py-3"><strong>{financialTypeLabel(tx.type)}</strong>{tx.description ? <span className="mt-1 block max-w-xs truncate text-xs text-muted">{tx.description}</span> : null}</td><td className="px-4 py-3"><span>{sourceTypeLabel(tx.sourceType)}</span><span className="block font-mono text-[11px] text-muted">{tx.sourceId.slice(0, 8)}</span></td><td className="px-4 py-3">{tx.direction === 1 ? "Giriş (+)" : "Çıkış (−)"}</td><td className={`px-4 py-3 text-right font-semibold tabular-nums ${tx.direction === 1 ? "text-emerald-700" : "text-rose-700"}`}>{tx.direction === 1 ? "+" : "−"}{formatMoney(tx.amount)}</td><td className="px-4 py-3 text-right font-bold tabular-nums">{formatMoney(tx.balanceAfter)}</td><td className="px-4 py-3">{isSafelyReversible(tx) && !reversedIds.has(tx.id) ? <TransactionLifecycleAction transactionId={tx.id} accountPath={accountPath} /> : <span className="text-xs text-muted">{reversedIds.has(tx.id) ? "Terslendi" : tx.sourceType === 4 ? "Ödeme detayından iptal edilir" : [20, 21].includes(tx.type) ? "Transfer bacağı ayrı terslenmez" : "Ters kayıt"}</span>}</td></tr>)}</tbody></table></div></section>;
}
