import Link from "next/link";
import type { BankAccount, CashAccount, TreasuryView } from "../types";
import { treasuryHref } from "../query";
import { formatMoney } from "../presentation";
import { TreasuryCommandForm } from "./treasury-command-form";

export function TreasuryWorkspace({ view, cashAccounts, bankAccounts }: { view: TreasuryView; cashAccounts: CashAccount[]; bankAccounts: BankAccount[] }) {
  return <div className="space-y-5"><nav aria-label="Hazine çalışma alanı" className="flex flex-wrap gap-2 rounded-xl border border-border bg-surface p-2">{([['accounts','Hesap defteri'],['manual','Manuel hareket'],['transfer','Banka transferi']] as const).map(([key, label]) => <Link key={key} href={treasuryHref(key)} aria-current={view === key ? "page" : undefined} className={`inline-flex min-h-10 items-center rounded-lg px-4 text-sm font-semibold ${view === key ? "bg-primary text-white" : "hover:bg-surface-subtle"}`}>{label}</Link>)}</nav>
    {view === "accounts" ? <AccountLedger cashAccounts={cashAccounts} bankAccounts={bankAccounts} /> : <TreasuryCommandForm view={view} cashAccounts={cashAccounts} bankAccounts={bankAccounts} />}
  </div>;
}
function AccountLedger({ cashAccounts, bankAccounts }: { cashAccounts: CashAccount[]; bankAccounts: BankAccount[] }) { return <div className="grid items-start gap-5 xl:grid-cols-2"><AccountSection title="Kasalar" description="Nakit hareketlerinin API tarafından hesaplanan güncel bakiyesi." kind="cash" accounts={cashAccounts} /><AccountSection title="Banka hesapları" description="Transfer ve banka hareketlerinin türetilmiş bakiyesi." kind="bank" accounts={bankAccounts} /></div>; }
function AccountSection({ title, description, kind, accounts }: { title: string; description: string; kind: "cash" | "bank"; accounts: (CashAccount | BankAccount)[] }) { return <section className="overflow-hidden rounded-xl border border-border bg-surface"><div className="border-b border-border px-5 py-4"><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm text-muted">{description}</p></div>{accounts.length ? <ul className="divide-y divide-border">{accounts.map((account) => <li key={account.id}><Link href={`/accounting/treasury/${kind}/${account.id}`} className="flex min-h-20 items-center justify-between gap-4 px-5 py-3 hover:bg-primary-soft/20"><span className="min-w-0"><strong className="block truncate">{account.name}</strong><span className="mt-1 block text-xs text-muted">{account.code}{"bankName" in account ? ` · ${account.bankName}` : ""} · {account.isActive ? "Aktif" : "Pasif"}</span></span><span className="shrink-0 text-right"><strong className="block tabular-nums">{formatMoney(account.balance, account.currencyCode)}</strong><span className="text-xs text-muted">API bakiyesi →</span></span></Link></li>)}</ul> : <div className="p-6 text-center text-sm text-muted">Henüz {kind === "cash" ? "kasa" : "banka hesabı"} yok.</div>}<div className="border-t border-border p-4"><Link href={`/accounting/treasury/new-${kind}`} className="inline-flex min-h-10 cursor-pointer items-center rounded-lg border border-primary px-4 text-sm font-semibold text-primary hover:bg-primary-soft/30">{kind === "cash" ? "Kasa oluştur" : "Banka hesabı oluştur"}</Link></div></section>; }
