"use client";

import Link from "next/link";
import { useActionState, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import { createBankTransferAction, createManualTransactionAction } from "../actions";
import { formatMoney } from "../presentation";
import type { BankAccount, CashAccount, TreasuryView } from "../types";
import { initialTreasuryFormState } from "../types";

export function TreasuryCommandForm({ view, cashAccounts, bankAccounts }: { view: Exclude<TreasuryView, "accounts">; cashAccounts: CashAccount[]; bankAccounts: BankAccount[] }) {
  const action = view === "manual" ? createManualTransactionAction : createBankTransferAction; const router = useRouter(); const formRef = useRef<HTMLFormElement>(null); const guard = useRef(false); const alertRef = useRef<HTMLDivElement>(null); const [state, formAction, pending] = useActionState(action, initialTreasuryFormState);
  useEffect(() => { if (state.redirectHref) { router.replace(state.redirectHref); router.refresh(); } }, [router, state.redirectHref]); useEffect(() => { if (state.status === "error") alertRef.current?.focus(); guard.current = false; if (state.refresh) router.refresh(); }, [router, state]);
  const rotate = () => { const hidden = formRef.current?.elements.namedItem("idempotencyKey") as HTMLInputElement | null; if (hidden) hidden.value = crypto.randomUUID(); };
  const today = new Date().toISOString().slice(0, 10);
  return <form ref={formRef} action={formAction} onInput={rotate} onSubmit={(event) => { if (guard.current) event.preventDefault(); else guard.current = true; }} className="mx-auto max-w-3xl rounded-xl border border-border bg-surface p-5"><input type="hidden" name="idempotencyKey" defaultValue={crypto.randomUUID()} />{state.status === "error" ? <div ref={alertRef} role="alert" tabIndex={-1} className="mb-4 rounded-lg border border-danger/30 bg-red-50 px-4 py-3 text-sm text-red-900"><strong>{state.message}</strong>{state.fieldErrors ? <ul className="mt-2 list-disc pl-5">{Object.values(state.fieldErrors).flat().map((message) => <li key={message}>{message}</li>)}</ul> : null}{state.traceId ? <span className="mt-1 block text-xs">Takip kodu: {state.traceId}</span> : null}</div> : null}<h2 className="text-lg font-semibold">{view === "manual" ? "Manuel finans hareketi" : "Atomik banka transferi"}</h2><p className="mt-1 text-sm leading-6 text-muted">{view === "manual" ? "Yalnız güvenli manuel işlem türleri sunulur. Bakiye elle girilmez; API hareketten türetir." : "Çıkış ve giriş bacakları aynı işlem anahtarıyla tek transaction içinde oluşturulur."}</p>
    {view === "manual" ? <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">İşlem türü *<select name="type" required className="mt-1.5 min-h-10 w-full rounded-lg border border-border-strong bg-surface px-3"><option value="10">Kasa girişi</option><option value="11">Kasa çıkışı</option><option value="40">Banka komisyonu</option><option value="41">Pazaryeri komisyonu</option><option value="50">İade</option></select></label><label className="text-sm font-medium">Finans hesabı *<select name="accountChoice" required className="mt-1.5 min-h-10 w-full rounded-lg border border-border-strong bg-surface px-3"><option value="">Hesap seçin</option><optgroup label="Kasalar">{cashAccounts.filter(a => a.isActive).map(a => <option key={a.id} value={`cash:${a.id}`}>{a.code} · {a.name} · {formatMoney(a.balance)}</option>)}</optgroup><optgroup label="Banka hesapları">{bankAccounts.filter(a => a.isActive).map(a => <option key={a.id} value={`bank:${a.id}`}>{a.code} · {a.name} · {formatMoney(a.balance)}</option>)}</optgroup></select></label><CommonFields today={today} /></div> : <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Kaynak banka *<select name="fromBankAccountId" required className="mt-1.5 min-h-10 w-full rounded-lg border border-border-strong bg-surface px-3"><option value="">Kaynak seçin</option>{bankAccounts.filter(a => a.isActive).map(a => <option key={a.id} value={a.id}>{a.code} · {a.name} · {formatMoney(a.balance)}</option>)}</select></label><label className="text-sm font-medium">Hedef banka *<select name="toBankAccountId" required className="mt-1.5 min-h-10 w-full rounded-lg border border-border-strong bg-surface px-3"><option value="">Hedef seçin</option>{bankAccounts.filter(a => a.isActive).map(a => <option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><CommonFields today={today} /></div>}
    <div className="mt-6 flex flex-wrap justify-end gap-2"><Link href="/accounting/treasury" className="inline-flex min-h-10 cursor-pointer items-center rounded-lg border border-border-strong px-4 text-sm font-semibold hover:bg-surface-subtle">Vazgeç</Link><button type="submit" disabled={pending} className="min-h-10 cursor-pointer rounded-lg bg-primary px-4 text-sm font-semibold text-white hover:bg-primary-hover disabled:cursor-not-allowed disabled:opacity-60">{pending ? "Kaydediliyor…" : view === "manual" ? "Hareketi kaydet" : "Transferi kaydet"}</button></div><p className="mt-4 text-xs leading-5 text-muted">Çakışma veya belirsiz ağ sonucunda otomatik tekrar yapılmaz; ilgili ekstre işlem anahtarıyla yeniden kontrol edilir.</p></form>;
}
function CommonFields({ today }: { today: string }) { return <><label className="text-sm font-medium">Tutar *<input name="amount" required inputMode="decimal" placeholder="0,00" className="mt-1.5 min-h-10 w-full rounded-lg border border-border-strong px-3" /></label><label className="text-sm font-medium">İşlem tarihi *<input name="transactionDate" type="date" required defaultValue={today} className="mt-1.5 min-h-10 w-full rounded-lg border border-border-strong px-3" /></label><label className="text-sm font-medium sm:col-span-2">Açıklama<textarea name="description" maxLength={500} rows={3} className="mt-1.5 w-full rounded-lg border border-border-strong px-3 py-2" /></label></>; }
