using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ECommerce.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddProductSeoAndUrlRedirects : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "IsAltTextAutoGenerated",
                table: "ProductImages",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.Sql(
                """
                UPDATE image
                SET image.[AltText] = product.[Title],
                    image.[IsAltTextAutoGenerated] = CAST(1 AS bit)
                FROM [ProductImages] AS image
                INNER JOIN [Products] AS product ON product.[Id] = image.[ProductId]
                WHERE image.[AltText] IS NULL OR LTRIM(RTRIM(image.[AltText])) = '';
                """);

            migrationBuilder.CreateTable(
                name: "ProductUrlRedirects",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ProductId = table.Column<long>(type: "bigint", nullable: false),
                    Url = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ProductUrlRedirects", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ProductUrlRedirects_Products_ProductId",
                        column: x => x.ProductId,
                        principalTable: "Products",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ProductUrlRedirects_ProductId",
                table: "ProductUrlRedirects",
                column: "ProductId");

            migrationBuilder.CreateIndex(
                name: "IX_ProductUrlRedirects_Url",
                table: "ProductUrlRedirects",
                column: "Url",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ProductUrlRedirects");

            migrationBuilder.DropColumn(
                name: "IsAltTextAutoGenerated",
                table: "ProductImages");
        }
    }
}
