using ECommerce.Domain.Entities;
using ECommerce.Domain.Enums;

namespace ECommerce.Application.StoreSettings.Dtos;

// Burada yönetim ekranlarının bütün düzenlenebilir mağaza ayarlarını taşıyorum.
public sealed record AdminStoreSettingsDto(
    string DisplayName,
    string? ShortDescription,
    string? LogoUrl,
    string? DarkLogoUrl,
    string? FaviconUrl,
    string? DefaultShareImageUrl,
    string? SupportEmail,
    string? SupportPhone,
    string? WhatsappNumber,
    string? ContactAddress,
    string? WorkingHours,
    string? MapUrl,
    bool ShowSupportEmail,
    bool ShowSupportPhone,
    bool ShowWhatsapp,
    bool ShowContactAddress,
    bool ShowWorkingHours,
    bool ShowMap,
    string? LegalCompanyName,
    string? TaxOffice,
    string? TaxNumber,
    string? NationalIdentityNumber,
    string? MersisNumber,
    string? TradeRegistryNumber,
    string? Country,
    string? City,
    string? District,
    string? AddressLine,
    string? PostalCode,
    string? DefaultTitle,
    string? TitleTemplate,
    string? DefaultDescription,
    string? DefaultOpenGraphImageUrl,
    bool AllowIndexing,
    string? FacebookUrl,
    string? InstagramUrl,
    string? TiktokUrl,
    string? YoutubeUrl,
    string? XUrl,
    string? PinterestUrl,
    StorefrontStatus Status,
    string? StatusMessage,
    bool ShowOutOfStockProducts,
    bool ShowProductsWithoutPrice,
    StorefrontProductSort DefaultProductSort,
    bool DefaultProductSortDescending,
    bool ShowCompareAtPrice,
    bool ShowStockWarning,
    int LowStockThreshold,
    Guid ConcurrencyToken)
{
    // Burada domain aggregate'ini yönetim DTO'suna dönüştürüyorum.
    public static AdminStoreSettingsDto FromEntity(ECommerce.Domain.Entities.StoreSettings settings) =>
        new(
            settings.DisplayName,
            settings.ShortDescription,
            settings.LogoUrl,
            settings.DarkLogoUrl,
            settings.FaviconUrl,
            settings.DefaultShareImageUrl,
            settings.SupportEmail,
            settings.SupportPhone,
            settings.WhatsappNumber,
            settings.ContactAddress,
            settings.WorkingHours,
            settings.MapUrl,
            settings.ShowSupportEmail,
            settings.ShowSupportPhone,
            settings.ShowWhatsapp,
            settings.ShowContactAddress,
            settings.ShowWorkingHours,
            settings.ShowMap,
            settings.LegalCompanyName,
            settings.TaxOffice,
            settings.TaxNumber,
            settings.NationalIdentityNumber,
            settings.MersisNumber,
            settings.TradeRegistryNumber,
            settings.Country,
            settings.City,
            settings.District,
            settings.AddressLine,
            settings.PostalCode,
            settings.DefaultTitle,
            settings.TitleTemplate,
            settings.DefaultDescription,
            settings.DefaultOpenGraphImageUrl,
            settings.AllowIndexing,
            settings.FacebookUrl,
            settings.InstagramUrl,
            settings.TiktokUrl,
            settings.YoutubeUrl,
            settings.XUrl,
            settings.PinterestUrl,
            settings.Status,
            settings.StatusMessage,
            settings.ShowOutOfStockProducts,
            settings.ShowProductsWithoutPrice,
            settings.DefaultProductSort,
            settings.DefaultProductSortDescending,
            settings.ShowCompareAtPrice,
            settings.ShowStockWarning,
            settings.LowStockThreshold,
            settings.ConcurrencyToken);
}
