using ECommerce.Domain.Enums;

namespace ECommerce.Application.StoreSettings.Dtos;

// Burada storefront'a yalnız güvenli kimlik, görünür iletişim, SEO ve davranış ayarlarını taşıyorum.
public sealed record PublicStoreSettingsDto(
    string DisplayName,
    string? ShortDescription,
    string? LogoUrl,
    string? DarkLogoUrl,
    string? FaviconUrl,
    string? DefaultShareImageUrl,
    string? SupportEmail,
    string? SupportPhone,
    string? WhatsappNumber,
    string? ContactAddress,
    string? WorkingHours,
    string? MapUrl,
    bool ShowSupportEmail,
    bool ShowSupportPhone,
    bool ShowWhatsapp,
    bool ShowContactAddress,
    bool ShowWorkingHours,
    bool ShowMap,
    string? DefaultTitle,
    string? TitleTemplate,
    string? DefaultDescription,
    string? DefaultOpenGraphImageUrl,
    bool AllowIndexing,
    string? FacebookUrl,
    string? InstagramUrl,
    string? TiktokUrl,
    string? YoutubeUrl,
    string? XUrl,
    string? PinterestUrl,
    StorefrontStatus Status,
    string? StatusMessage,
    bool ShowOutOfStockProducts,
    bool ShowProductsWithoutPrice,
    StorefrontProductSort DefaultProductSort,
    bool DefaultProductSortDescending,
    bool ShowCompareAtPrice,
    bool ShowStockWarning,
    int LowStockThreshold)
{
    // Burada aggregate'i gizli iletişim ve tüm yasal alanları çıkartarak public DTO'ya dönüştürüyorum.
    public static PublicStoreSettingsDto FromEntity(ECommerce.Domain.Entities.StoreSettings settings) =>
        new(
            settings.DisplayName,
            settings.ShortDescription,
            settings.LogoUrl,
            settings.DarkLogoUrl,
            settings.FaviconUrl,
            settings.DefaultShareImageUrl,
            settings.ShowSupportEmail ? settings.SupportEmail : null,
            settings.ShowSupportPhone ? settings.SupportPhone : null,
            settings.ShowWhatsapp ? settings.WhatsappNumber : null,
            settings.ShowContactAddress ? settings.ContactAddress : null,
            settings.ShowWorkingHours ? settings.WorkingHours : null,
            settings.ShowMap ? settings.MapUrl : null,
            settings.ShowSupportEmail,
            settings.ShowSupportPhone,
            settings.ShowWhatsapp,
            settings.ShowContactAddress,
            settings.ShowWorkingHours,
            settings.ShowMap,
            settings.DefaultTitle,
            settings.TitleTemplate,
            settings.DefaultDescription,
            settings.DefaultOpenGraphImageUrl,
            settings.AllowIndexing,
            settings.FacebookUrl,
            settings.InstagramUrl,
            settings.TiktokUrl,
            settings.YoutubeUrl,
            settings.XUrl,
            settings.PinterestUrl,
            settings.Status,
            settings.StatusMessage,
            settings.ShowOutOfStockProducts,
            settings.ShowProductsWithoutPrice,
            settings.DefaultProductSort,
            settings.DefaultProductSortDescending,
            settings.ShowCompareAtPrice,
            settings.ShowStockWarning,
            settings.LowStockThreshold);
}
